### ISSUE TITLE
Allow using the addon without connecting to Google Drive

### ISSUE THREAD

**Issue by cwesterfield** [sabeechen/hassio-google-drive-backup#124]
I'm attempting to use this very nice looking tool for auto snapshots only. I don't need the google drive functionality. I disabled the upload, but it still wont proceed until I link it with google. 

Is there a file I can create or something to get past the "Get Started Page"?

Thanks!

**Comment by sabeechen** [comment]
There isn't a way right now, which I agree is an oversight.  The reason why is complicated, but tl;dr is that its difficult to do because of how I coded up the addon.  I'll try to make a pass at adding the ability to bypass driv elogin in the next version, but in the meantime if you don't want to connect with your real Google account you'll have to create a dummy empty one (eg just sign up with a random username) and connct that instead.

**Comment by Jeltel** [comment]
I would also like to use this. Since I don't want my whole home assistant (with addons) on the google drives. And I have my own home cloud and backup setups.

So if you would like to put some effort into this. I would be willing to help testing.

**Comment by tomaae** [comment]
Same, I have my own global backup solution and just want a snapshot management.

**Comment by marcgarciamarti** [comment]
Same here. I've enabled password protection but I would appreciate it if one could opt out of uploading the backup to Google.

**Comment by sabeechen** [comment]
Took me a while, but I just released this in v0.103.0.  Now if you select the option to disable upload to Drive, it will bypass the screen that asks you to connect with Drive and the addon should function normally otherwise.
