### ISSUE TITLE
Can't add the repository

### ISSUE THREAD

**Issue by tiberius25** [sabeechen/hassio-google-drive-backup#127]
Hi, i'm trying to add the repository by copypast the URL: https://github.com/sabeechen/hassio-google-drive-backup. The ring of the process is spinning but nothing is happening at the end. The repository is not added. I tried it on 2 different hassios (hassio RP3 b+ 0.100.3 and hassio on docker 0.101.3). There are no errors in the log.

**Comment by openforest** [comment]
Yep, same problem here.

**Comment by sabeechen** [comment]
I tried adding it removing the addon from one of my testing instances ( running in docker) and didn't run into any trouble, so I suspect whatever is wrong is specific to your machines.  Did you check the Hass.io system log too ("Hass.io" > "System" > "System Log" > "Refresh")?  Thats the most likely place for error messages to show up.

**Comment by marcelkhalaf** [comment]
Same for me its take time to add the repository.
I can see it after restart hassio but i cant install it
The ring of the process turn for 2 seconds and install button blink once in red abd stop.  See below error in log
![Screenshot_20191111-234114_Chrome](https://user-images.githubusercontent.com/51001249/68623381-09632f00-04dd-11ea-9f36-b0f21f4e7965.jpg)

**Comment by tiberius25** [comment]
Today i just tried again and it works! The repository added ind the addon installed. Didn't do anithing...

**Comment by bcameron21** [comment]
I am having the same issue. Repository won't add.

`19-11-16 10:17:27 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/sabeechen/hassio-google-drive-backup repository
19-11-16 10:18:05 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_53qxGc: No such file or directory
fatal: index-pack failed
'.
19-11-16 10:18:05 ERROR (MainThread) [hassio.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup`

**Comment by sabeechen** [comment]
I tried re-adding the repo and installing on a fresh version of Hass.io and didn't run into problems.  I also haven't really changed anything in the addon recently, which together leads me to think this is actually a problem in Hass.io.  It looks like in this thread you guys are having at least two problems and here is the research I've been able to find on the problems:

1. To add a repository, Hass.io reads the the addon's configuration from Github.  Under the hood, Hass.io just runs git from the command line to accomplish this.  For some reason, that is failing for @bcameron21 .  At least one user has had this problem with this addon in the past ([reference](https://github.com/sabeechen/hassio-google-drive-backup/issues/62)), and I can find [many](https://www.reddit.com/r/homeassistant/comments/8l5rql/fresh_hassio_install_on_pi3_fails_to_clone/) [references](https://www.reddit.com/r/homeassistant/comments/8l5rql/fresh_hassio_install_on_pi3_fails_to_clone/) to it happening for [various](https://github.com/home-assistant/hassio-addons/issues/303) addon's in Hass.io for a while.  Unfontunately I can't find anyone who foound a way to reliably resolve it and instead people have resorted to some combination of restarting Hass.io, restarting the host machine, reflashing Hass.io, or just trying again later.  It seems like things just fix themselves after a while for most, and I have no idea why.

2. Every addon in Hass.io (this one included) runs inside of a Docker container, which is kind of like an isolated virtual machine inside of your Home Assistant machine.  This system has bugs and can get corrupted, which is what I think @marcelkhalaf is seeing.  I can find [a lot](https://duckduckgo.com/?q="Can't+install"+"readlink"+docker+site%3Agithub.com) of issues opened in other addons where people have the same problem.  For at least one user the issue was that their SD card was almost out of space (which means docker couldn't download the addon image) but the only sure-fire remedy I could find was to make a snapshot, wipe the installation, and restore.

**Comment by sabeechen** [comment]
Also, make sure you're running the latest version of Hass.io, I don't know if they've worked on this specifically but bugs get fixed all the time.

**Comment by sabeechen** [comment]
Closing this due to age, but if anyone is still running into problems with the latest version of Hassio give me a shout and I'll try to figure it out.
