### ISSUE TITLE
Snapshot.stale errors in log

### ISSUE THREAD

**Issue by PaulAntonDeen** [sabeechen/hassio-google-drive-backup#132]
I'm on Hass.io, the latest version using this addon 0.99.0 and am using lets encrypt ssl certificates.
I get the following errors in the hass.io system log at reboot:
```
19-11-25 11:02:01 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-11-25 11:02:01 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
```
I've tried enabling and disabling ssl in the config of this addin, no change in the log.

**Comment by namexless** [comment]
Same here

```
19-12-23 15:50:03 ERROR (MainThread) [hassio.utils] Can't execute restart while a task is in progress
19-12-23 15:50:05 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-12-23 15:50:05 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
19-12-23 15:50:33 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
```

**Comment by vash3d** [comment]
Same issue for me on Hassio.

**Comment by Zixim** [comment]
Same here

**Comment by PRES1005** [comment]
Same here, and it’s causing a restart of hassio every time. I run hassio in docker on a RPi4 if it can help

**Comment by sabeechen** [comment]
The addon doesn't communicate with Home Assistant over the network, it uses a proxy that Hass.io provides.  The detalils of how this works are [here](https://developers.home-assistant.io/docs/en/hassio_addon_communication.html#home-assistant).  The error you're seeing:
```
19-11-25 11:02:01 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-11-25 11:02:01 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
```
Means that Hass.io is unable to communicate with Home Assistant on behalf of the addon.  Normally this is because Home Assistant is restarting or just booting up and can be ignored.  Hass.io doesn't expose a way for my addon to check to see if Home Assistant is running or not, so the only way to see if its available is to send a request, which will cause this error to be displayed when it is down.

The reason the addon attempts to contact Home Assistant at all is to publish the staleness sensor and send notifications if backup fails.  If you want to get rid of this error message, entirely, the only way is to [disable those sensors](https://github.com/sabeechen/hassio-google-drive-backup#example-turn-off-notifications-and-staleness-sensor)

**Comment by fi-sch** [comment]
Thanks for explaining🙏🏻 I did not experience any other issue than this error in logs. Everything works perfectly :)

**Comment by sabeechen** [comment]
Sounds good, let me know if something doesn't look right.
