### ISSUE TITLE
Previous version backups do not appear in the UI

### ISSUE THREAD

**Issue by MarcJenningsUK** [sabeechen/hassio-google-drive-backup#137]
Backups/snapshots from previous versions do not appear in the UI.  I can upload new snapshots to Drive, but not pull existing ones back

**Comment by sabeechen** [comment]
Did you reinstall the addon, or is this just from an upgrade?
If you reinstalled, do you use [your own client id and secret](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md) when you connect the addon to Drive?

If yes to both of these, then make sure you use the same client id an secret both times.  Otherwise, Google considers the addon a new app and won't let it see the snapshots/folders created with a the "different" app.

Either way, can still get the old snapshots back into Home Assistant by copying them to the /backup folder in Home Assistant.

**Comment by sabeechen** [comment]
Closing this out due to age, but if you think there is more I can do to help, feel free to reopen.
