### ISSUE TITLE
Snapshot appears to stuck trying to create

### ISSUE THREAD

**Issue by franmiele** [sabeechen/hassio-google-drive-backup#143]
I have a snapshot that has been running for hours. I tried a restart and a reboot of my HA system, but it still sitting the "pending" status.

How can I fix this?

**Comment by sabeechen** [comment]
Many things could cause this.

The most likely reason is that your snapshot are massive, and the most common reason snapshots are massive is because of a huge sensor database.  If you're running Hass.io on something like a raspberry pi on an SD card, it will often take hours to compress a snapshot thats just a few GB.  If thats the problem you'll see a really big file named <path to config dir>/.homeassistant/home-assistant_v2.db".  I have some tips [here](https://github.com/sabeechen/hassio-google-drive-backup#will-this-fill-up-my-google-drive--why-are-my-snapshots-so-big) that might help.  Note that purging a huge sensor database can also take hours and sometimes days, depending on the size.  Its really slow!

Another problem could be that your drive may be out of space.  You can set up the [system monitor ](https://www.home-assistant.io/integrations/systemmonitor) component to track disk usage to see if thats your problem.

If snapshot creation is failing, then you should see errors printed out in the Hass.io system log.  You can get to that by navigating to "Hass.io" -> "System" -> "System Log" from within the Home Assistant.  When a snapshot is being created, it will periodically print out message about what its doing.  That might give you more details about whats taking so long.

Hope that helps!

**Comment by sabeechen** [comment]
I'm closing this due to age, but feel free to reopen if you think there is something else I can help with.
