### ISSUE TITLE
Stop/cancel active Google Drive sync?

### ISSUE THREAD

**Issue by crowbarz** [sabeechen/hassio-google-drive-backup#147]
Is it possible to stop a currently running sync to Google Drive?

After installing the addon and setting up my Drive access credentials, I was trying to troubleshoot why the big red multiple delete warning didn't disappear after settings were modified to avoid the deletes. Then I noticed that the addon was actively uploading 3.6GB of pre-existing snapshots to Drive. Also, after realising that I had asked the addon to upload far more data than originally intended, I lowered the number of snapshots saved on Drive in settings. That setting change didn't take effect, presumably due to the sync already running.

As I couldn't see any other way of cancelling the sync, I restarted the addon from the hass.io addon panel. The big red warning then went away, plus the new snapshots to keep setting for Drive took effect.

Is there a better way to stop an active sync than restarting the addon, and if so then can saving the settings also stop any currently active sync? I saw in the log that saving settings automatically triggers a sync, but that doesn't do anything if there's a sync already running.

**Comment by sabeechen** [comment]
Man, I'd really like this too.  I've had the exact same thing happen to me, and the only way to stop it is to restart the addon like you did.  The problem is I really didn't plan to have this feature when I started writing the addon, and the way python works (the language the addon is written in) makes it pretty time consuming to add in after the fact.

I'll do a little digging to see what kind of effort it would be to change.  No promises though.

**Comment by crowbarz** [comment]
If it isn't easy to implement stop in the addon itself, then given how infrequently this occurs (and how nobody seems to have asked for this before!) then what about throwing a warning when settings are saved that says something like "Settings will take effect after the current sync has completed or when the addon is restarted". If your FE supports it, maybe the warning could additionally show a link to restart the addon, perhaps via a deep link to the hass.io UI, via a call to the hassio.addon_restart service, or triggering a restart of the docker container.

Currently, an error is shown in the UI only if you select Actions >  Sync Now whilst a sync was already running, and _not_ when a sync is attempted after you save settings (it just says "Settings saved"). An error does appears in the log though, and that's how I figured out what was going on.

**Comment by GoSpursGoNL** [comment]
I encountered the same problem. I noticed that when I force-stop the addon, and restart it again, it remembers that it was backup up / uploading and continues. Would it be possible to delete temporary files (where are they stored) between stopping and starting, as a manual way to cancel a backup action?

**Comment by sabeechen** [comment]
Right now I'm in the middle of writing the logic to do this, I opted to do the more time consuming way I described above since it also lets me clean up a bunch of more "sketchy" parts of the codebase.  Since its a relatively large change I'm taking my time to make sure everything still works right.  So its coming, just slowly.
The addon doesn't actually store any temporary files.  If you fully stop and restart it, any partial upload should restart from the beginning.

**Comment by GoSpursGoNL** [comment]
Thanks for that! But how does the addon remember after a restart that it had unfinished business?

**Comment by sabeechen** [comment]
It looks at whats in Google Drive and whats in Home Assistant, and uploads anything missing to Google Drive.

**Comment by sabeechen** [comment]
Took me a while, but I finally go this implemented.  In the latest version of the addon a notification shows up in the UI any time a sync is happening.  It includes a button to "cancel" the sync, which will pause backup for one hour (or until you resume it).
