### ISSUE TITLE
Unable to reach Hassio supervisor

### ISSUE THREAD

**Issue by CSnipper** [sabeechen/hassio-google-drive-backup#163]
Clean install on newest hassio in docker. Does not works :(

Supervisor is running

`03-11 14:47:24 CRITICAL Unable to reach Hassio supervisor.
03-11 14:47:24 CRITICAL 
Traceback (most recent call last):
  File "/app/backup/__main__.py", line 57, in main
    ha_source.init()
  File "/app/backup/hasource.py", line 227, in init
    self._refreshInfo()
  File "/app/backup/hasource.py", line 244, in _refreshInfo
    self.self_info = self.harequests.selfInfo()
  File "/app/backup/harequests.py", line 70, in selfInfo
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "addons/self/info")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='hassio', port=80): Max retries exceeded with url: /addons/self/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f25befd4880>: Failed to establish a new connection: [Errno 13] Permission denied'))`

**Comment by sabeechen** [comment]
Thats a pretty strange error to get.  If I'm reading it correctly, the OS is refusing to let the addon make web requests (thats the "Permission denied" at the end).  The addon needs to be able to do this to function even minimally.
Its unusual because Hass.io is supposed to create an enviornment in Docker that avoids this kind of problem.  I suspect this is actually a problem in Hass.io.  Some suggestions:

- Check the supervisor logs (*Supervisor* > *System* > *System Logs* > *Refresh*) right after restarting the addon.  Its likely to print out some error message that can shed light on the problem.
- Restart the addon.  If that doesn't work, restart the supervisor.  If that doesn't work, restart the host machine.

Some other questions that might help me narrow down whats causing this:
- What environment are you running Home Assistant on? (eg a rapsberry pi, in a VM, on top of ubuntu, etc).  
- Do you have anything "custom" running on your Home Assistant machine that might limit the permissions of the software running on it?

**Comment by CSnipper** [comment]
It is in the docker on Intel I3 machine with OMV installed (debian). Hassio image is running"in pivileged mode".

**Comment by sabeechen** [comment]
Did you try the things I recommended?  The supervisor logs are likely to have answers and if its a problem with the container Hass.io creates for the addon then restarting the supervisor is likely to fix things.

**Comment by sabeechen** [comment]
Closing this for now, but please reopen if you think there is more I can help with.
