### ISSUE TITLE
Not backing up configuration

### ISSUE THREAD

**Issue by SamPhoenix91** [sabeechen/hassio-google-drive-backup#171]
My configuration is not being backed up, not sure if this is a bug or on purpose (for size reasons) as there is nothing documented about it (from what I could see).

I almost lost my configuration and think it should either be made very clear that is it not being backed up, or give the option if this is not a bug.

**Comment by sabeechen** [comment]
I'll need some more information to understand what's going wrong.
* Do you mean that your configuration.yaml isn't being in luded in your snapshots?
* Do you mean that your configuration.yaml wasn't restored when you restored a snapshot?
* Do you mean some other configuration wasn't backed up?
* Please double check that you aren't making partial snapshots, which you can configure to exclude various parts of your configuration.
* If you did a restore, please double check that you did a *full* restore, since partial restores can be done in a way that doesn't restore some configuration.

It could help as well if you post your add-on configuration

**Comment by SamPhoenix91** [comment]
![image](https://user-images.githubusercontent.com/35844898/77788010-6b6d9c80-7058-11ea-98e4-83cbbc8267e7.png)
My full snapshots do not include "Home Assistant Configuration" - so my yaml files aren't being backed up.

**Comment by sabeechen** [comment]
That's peculiar.  The add-on depends on the supervisor to create that snapshot, and since it created a full snapshot the home assistant configuration should have been included.  I suspect this is a problem with the supervisor and not the add-on.
* Do you see any errors in the supervisor logs (Supervisor > System> Logs) after you click refresh on the supervisor snapshots page?  If there is a problem loading the snapshot, it should show up there.
* Do you see this in every snapshot the add-on makes?
* If you make a snapshot manually (through the supervisor snapshot page) does it still not have the home assistant config?
* If you download and open the snapshot archive, does it have a homeassistant.tar.gz file inside?

**Comment by SamPhoenix91** [comment]
I have manually created a snapshot and it has taken the configuration and it has the config (recognized on backup and restore end) and both snapshots have homeassistant.tar.gz

I just checked and a backup from the 24th does have the config (though not sure how to check if it was manual or automatic)

**Comment by Dilbert66** [comment]
I have the same issue.  Manually created snapshots in your app include the home assistant config folder.  Scheduled ones are  missing it.  It's been consistent over two cycles now.  I'm using the hassio ova in a vm.

**Comment by Dilbert66** [comment]
Automated backup sample restore screen view:
![image](https://user-images.githubusercontent.com/7193213/86067118-07d18180-ba42-11ea-8c26-1655dead39ba.png)

Manual back sample view:
![image](https://user-images.githubusercontent.com/7193213/86067207-51ba6780-ba42-11ea-876c-f33a87d74153.png)

**Comment by sabeechen** [comment]
I strongly suspect this is a problem in the supervisor, since the addon doesn't change the request it makes to the supervisor unless you've changed its configuration in the meantime, and the only way it excludes the config folder is if you tell it to create partial snapshots.  Can one of ya'll seeing this problem get me the supervisor logs (Supervisor > System > Logs) from when it creates one of broken snapshots?  It should have a bunch of message about backing up addons and creating tar files.  I'm guessing there is going to be an error printed there that explains what is going wrong.

**Comment by Dilbert66** [comment]
ok, dug through for the logs of that day and found an error that seems to be the issue. Not sure why this is not a problem with the manual backups.  Also the shm file is technically a temp file so should not be backed up.
![image](https://user-images.githubusercontent.com/7193213/86123802-21a5af80-baa8-11ea-8f9d-dad6a9942459.png)

**Comment by sabeechen** [comment]
I believe this has been resolved in Home Assistant, but please reopen if you think there is a way I can further help.
