### ISSUE TITLE
Exclude folders config and frontend editor

### ISSUE THREAD

**Issue by dede34fr** [sabeechen/hassio-google-drive-backup#174]
Hi, I would like to exclude some subfolders from /share, like share/camera.
When I did it, it worked but when setting up the generational backups via the frontend editor, it only allows to exclude the entire "share" folder and that action replaced my previous configuration option.
`exclude_folders: 'share/camera'`

**Comment by jd1900** [comment]
I have the same problem.

I have this line:
exclude_folders: "share/media"

But if I save any Config in the UI, it dissapears, as "share/media" is a subfolder of "share".
There I have a few GB, so it can be fatal.

**Comment by sabeechen** [comment]
when I wrote this addon, I assumed the Hass.Supervisor API only lets you entirely include or exclude 4 specific folders (thats how the supervisor's UI makes it look), but looking at the source now I don't think thats actually case.  I'll look into adding this.

**Comment by sabeechen** [comment]
Ah, turns out I was mistaken.  The supervisor only lets you include/exlcude those 4 specific folders wholly (see [the code](https://github.com/home-assistant/supervisor/blob/5fdc340e580805cfdcc5a2b1662948ba8d0bf4a7/supervisor/snapshots/validate.py#L36)).  In order for me to allow this in the addon (which I'd be happy to implement in the addon once supported) support would need to be added in the Supervisor.
