### ISSUE TITLE
Missing sensor.snapshot_backup after upgrading to from 0.109.1 to  0.109.4

### ISSUE THREAD

**Issue by reesion** [sabeechen/hassio-google-drive-backup#185]
Hi,

I noticed sensor.snapshot_backup is missing after upgrading Hass.io from 0.109.1 to  0.109.4

Is there something i need to do?

**Comment by sabeechen** [comment]
This is most likely because of how Home Assistant handles the "transient" sensors that this addon creates.  The addon doesn't know when Home Assistant is restarting (eg for your upgrade) so it just has to poll every once in a while to see when its back up.  So when you restart, the sensors won't exist yet until the addon notices Home Assistant is back up and can publish them.  Usually this happens within 5 minutes.

I'd bet that the sensor is already back now, but if not you can click "Actions" -> "Sync Now" in the addon and you shoudl see it pop up.  If not, the addon logs should have an error message explaining why.

**Comment by reesion** [comment]
Thank you for explaining. Yes, sensor is already back.
