### ISSUE TITLE
permanent delete needed as bin equates to full drive

### ISSUE THREAD

**Issue by magiva** [sabeechen/hassio-google-drive-backup#187]
Example:
Standard drive is 15gb
1 backup is 5gb
settings are to keep 1 backup on google.
backup is every week.
drive is full in 3 weeks, 2 deleted + 1 live.
Even if the backups are deleted, they are only moved to the bin, google still equates the size of the bin to the total drive size and reports that the drive is full

the fix is to set upload period to 1 or 2 every 30 days
if there is a way to call a permanent delete then that would be better also

**Comment by sabeechen** [comment]
I'm clearing out old bugs and I'm surprised I never commented on this.  The addon doesn't move deleted items to the trash, it always permanently deletes them (unless you're using a shared drive, which has unlimited storage anyway).  I'm not quite sure what this bug is about.  If there is something  else you think I can help with, feel free to reopen this bug and I'll do what I can.
