### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by r3mcos3** [sabeechen/hassio-google-drive-backup#19]
Thank you for this amazing addon!

But are you planning to support ingress?
https://www.home-assistant.io/blog/

Thank you

**Comment by sabeechen** [comment]
Plan to, I'll just have to sort out how to do it without breaking everybody who hasn't updated yet.   Might give it a good while to let people get on board with the recent releases first.

**Comment by r3mcos3** [comment]
Ok, thnx for you're quick response :+1:

**Comment by sabeechen** [comment]
I've done a lot of messing around with ingress enabled on various versions of Home assistant, and I think I'm going to need to wait a while before I can turn it on without making a hassle for at least some of my users.  Many versions of Home Assistant below the official ingress supported version (0.91.3) recognize that and add-on has ingress enabled but error out when trying to render the ingress-ed page.

This puts me in a position where I can either require the latest version of HA forcing users to upgrade HA if they want the latest version of the add-on, or I can enable it without requiring the latest version which would make a broken experience for those with HA before 0.91.3.

I might be missing something, but I don't think the Hassio folks gave add-on developers a backwards-compatible upgrade path for supporting ingress.  Looking through the forum, it seems there is a lot of turmoil with the breaking changes involved with the add-ons that did update, so I'm going keep this shelved for a little while and see how things play out.

**Comment by r3mcos3** [comment]
Ok, fair answer! The addon works great, if you think it's not the right step to take now, Maybe I see it in the future, keep up the good work 👍

**Comment by mattkerrison** [comment]
+1 Ingress support would be great

**Comment by ACJ132** [comment]
I recently upgraded my hassos installation to use the Nabu Casa Cloud service for security. I was getting a lot of failed logon attempts from unknown IP addresses and wanted to be able to close the ports on my router. Nabu Casa allows me to have external access without using port forwarding. However, after switching over to Nabu Casa I am not longer able to access the Google Drive Backup UI. When I click on Open UI in the Add-on it says site cannot be reached. I tried using my local ip address to access and got the same error message. Does anyone know how I can access the UI when using Nabu Casa for Remote Access?

**Comment by marrobHD** [comment]
+1 I am also ingress

**Comment by 31337Ghost** [comment]
@sabeechen you could also create additional _dev_ repository with version which supports ingress. Any case thank you for your great work 🙌

**Comment by ronmichel** [comment]
Thank you for the addon! Ingress would be very welcome!

**Comment by sabeechen** [comment]
Took me a while to get there, but I've enabled ingress in the latest release, v0.98.1.  Make sure you refresh the add-on store page to make Hass.io see the update faster if you'd like to update now, and let me know if you run into trouble.

Upgrading an add-on to support ingress has caused a lot of confusion for users in the past since the "old" way of access the web UI from an exposed port usually gets turned off.  To mitigate that, if you're upgrading the add-on from an older version you'll see a dialog in the web-ui asking if you'd like to switch over to access the UI through ingress only.  The web-ui will still be available from the "old" port until you choose, and the choice can be changed from the setting menu at any time.
