### ISSUE TITLE
[Feature Request] Google drive backup for recorded videos of IP cam

### ISSUE THREAD

**Issue by majkers** [sabeechen/hassio-google-drive-backup#195]
Hello,
First of all, great job with this addon!!! One more question about feature request. Is it possible to do the same addon ie. gdrive backup but for the files stored by IP cam in local netword that can be accessed via ftp for example? I would like to store my recordings on google drive but there isn't htat feature from camera's firmware. Cheers

**Comment by sabeechen** [comment]
I'm closing all of the issues open relating to backup of non-snapshot files as I'm making a call on it.  I don't intend to support this in the future.  
With the addon I'm always trying to balance ease-of-use, flexibility, the amount of time I spend supporting it, and the most widely requested features.  This means I often have to cut something out (or turn down features) in order to maintain the other priorities.  Being able to back up other files would be a good feature, but I don't think I'd be able to put in the time to make it work well while also keeping the addon simple to configure.  In the future I'd like to focus on supporting snapshot backup to other cloud providers instead.

As an alternative, I might suggest checking out [samccauley's backup addon](https://github.com/samccauley/addon-hassiogooglebackup/).  Its been around longer than mine, is a little more difficult to configure, but it gives you much more flexibility in deciding what files to sync.  It might be able to backup the files you want in a similar way.
