### ISSUE TITLE
Exclude sub folders within config/www

### ISSUE THREAD

**Issue by geyles** [sabeechen/hassio-google-drive-backup#196]
I've tried and better tried but some CCTV snaps in my www I don't want backing up. I've used:

exclude_folders: 'config/www/garden'

Changing the config to local and a few other versions but they still get included in the backup.

**Comment by sabeechen** [comment]
Right now the addon can only exclude 4 whole root folders (config, ssl, share, local addons).  I'm working on making it able to exclude subfolders (#178) though I'm not 100% sure yet that Home Assistant's API supports it.

**Comment by sabeechen** [comment]
Unfortunately, it looks like the supervisor will only let you include/exclude those 4 folders wholistically from a snapshot (see the [code](https://github.com/home-assistant/supervisor/blob/5fdc340e580805cfdcc5a2b1662948ba8d0bf4a7/supervisor/snapshots/validate.py#L36)`) so in order to support this it would have to be implemented in the supervisor.  I'd gladly do that on my side once its implemented, but I'm not certain how difficult this functionality would be to add in the supervisor.

**Comment by shannonhochkins** [comment]
Is this still not possible @sabeechen ? The backup functionality seems to have changed a lot, @geyles did you solve this a different way? Having the exact same issue with my cameras being in www with a local website reading these files

**Comment by geyles** [comment]
@shannonhochkins no I didn't solve it. I ended up having frigate on a separate device and storing snapshots and clips on a NAS device.

**Comment by shannonhochkins** [comment]
Were you reading these files from a website running in the www folder? If so, how did you make requests externally, remotely ?
