### ISSUE TITLE
addon complains about drive being full, but there is only 6.6 GB on Google Drive (out of 15)

### ISSUE THREAD

**Issue by fribse** [sabeechen/hassio-google-drive-backup#203]
Addon: 0.100.0
HA: 0.111.4

I've had to make a seperate google account for my backups, so in that account there is only Backup's on the particular google account.
The drive says it is 6.6 GB filled up (out of 15), and it holds two backups.
But in the add on page, it complains that the drive is almost full, and will not backup. I can't make it sync unless I force it.

**Comment by sabeechen** [comment]
Sorry it took so long to get back to you on this, I've had some stuff going on.
The only reason the add-on can display this error (the "Google Drive is Full" message) is if the add-on attempted to upload the snapshot and google rejected it.  So we can be certain that Google "thinks" you don't have enough space for the most recent snapshot.  A few of the more common reasons for this could be:

* If you have the add-on to configured to store "N" snapshots in Google Drive, then it will need the space to store "N+1" since the oldest snapshot doesn't get deleted until the newest one is uploaded.  It sounds like this might be your problem, if two backups are using 6.6 GB and each is 3.3 GB, then you'd need 9.9 GB to backup the two of them.
* Your latest snapshot is unusually large, or has just been growing steadily.  You should be able to see on the add-on's Web UI what the size of the latest snapshot is.
* Other Google properties can consume space (Photos and GMail for example) and it isn't always reflected in storage used percentage on drive.google.com.  Sicne this is a new account with just the backups, this is unlikely to be the problem.

**Comment by sabeechen** [comment]
Closing this for now, but if you still run into trouble let me know and I'll look into this further.
