### ISSUE TITLE
Backups not containing all files. 

### ISSUE THREAD

**Issue by ASNNetworks** [sabeechen/hassio-google-drive-backup#204]
This is kind of a major issue. I notice a lot of backups miss a lot of files inside the backup. The sizes are different and I extracted a few to investigate. Found of lot of files are missing. Unfortunately I found out about this when I tried to restore to my latest backup... Having to restore to a backup of a few days ago (luckily I created a manual update then when I overhauled my UI). 

I noticed the size differences a long time ago (more then a few months) but never thought anything of it. I re-installed the add-on last week and re-paired my Google Drive, still am getting different sizes of backups. Full backup should be 150MB, while a lot of them are 70MB. And just to clarify, I extracted a few backups and noticed actual files and folders missing completely. In fact, all my UI .yaml files were not there :( 

I'm not sure the bug has anything to do this the add-on itself though. I don't know how the backup process works exactly. Perhaps Home Assistant has a bug with automated backups and this add-on merely triggers and uploads them to Google Drive.

**Comment by sabeechen** [comment]
I've had a few users report this recently, I've seen it to on my home instance too.  It appears that this is a bug in the supervisor, (issue [here](https://github.com/home-assistant/supervisor/issues/1633) and the fix [here](https://github.com/home-assistant/supervisor/pull/1795)).  I trust the fix will be included in the next release (if it hasn't already).  Since this addon depeneds on the supervisor to actually create the snapshots, there isn't anything I can do from this side to resolve it in the meantime.
