### ISSUE TITLE
unencrypt tar.gz files

### ISSUE THREAD

**Issue by nelbs** [sabeechen/hassio-google-drive-backup#210]
I like the feature to encrypt the snapshots  but is it also possible to unencrypt the tar.gz files so I can inspect the files on my computer? I tried winzip and 7zip but that didnt work..

**Comment by sabeechen** [comment]
I haven't been able to find a tool that unzips them either.  I suspect writing a small tool to decrypt them is possible, but I ahven't invested the time to explore it.  If anyone would like to take a crack, [here ](https://github.com/home-assistant/supervisor/blob/2658f95347ac2e4b2d2256a2fe44579acce64c27/supervisor/snapshots/snapshot.py#L200)is the part of the supervisor that seems to do the magic.

**Comment by sabeechen** [comment]
I've looked into this a bit more, and it looks like the supervisor actually creates password protected snapshots as an unencrypted tar, but then each addon and folder embedded inside it is encrypted using a custom class called [SecureTar](https://github.com/home-assistant/supervisor/blob/2658f95347ac2e4b2d2256a2fe44579acce64c27/supervisor/utils/tar.py#L27).  This seems to me like a very odd way to do it, I'm not sure why they didn't just use one of the standard password protected archive formats.

Regardless, to decrypt these someone would have to write a new tool that makes use of this code and keep it in sync with any changes they make in the supervisor.  While this isn't super complicated, its not something I can take on at this time.  I'm closing this for now since it isn't something that would make sense to implement in my addon, but I'll keep it in mind for the future if I'm ever looking for a new project.
