### ISSUE TITLE
Suggestion: similar tool to backup some folder (security images, for example)

### ISSUE THREAD

**Issue by McGiverGim** [sabeechen/hassio-google-drive-backup#213]
This is only a suggestion for a "new" addon for Home Assistant.

I think this is one of the best addons, and now that you have the framework to do it, I think it will be useful if you can create a new to backup to Google Drive any other kind of file. Maybe publishing a service in Home Assistant to trigger the backup of a folder or a file or directly syncing a folder to Google Drive.

This can be very useful for security images, if the alarm is triggered, I take images and videos but I want them to be in the cloud as soon as possible too, preventing the theft from removing the card or the complete raspberry.

I can throw a complete backup but it will take a lot of time.

**Comment by sabeechen** [comment]
This is a good idea, and I'm sure lots of people could make use of it, but I'll be straight with you and say I'm not going to do it.  My reasons are:
- Keeping the purpose of this addon simple (ie, backup snapshots to the cloud) is a big part its the appeal.  The HA ecosystem is full of complex swiss army knives that solve any problem, but they sacrifice ease-of-use for their flexibility.  This addon is easy for (most) to use because it only attempts to solve a handful of problems.
- I have a limited amount of time to support this addon and for the year and change its been alive that time has been more than filled just supporting the basic feature set it has.   I have to be careful how much functionality I support and keep updated with changes to HA, Google Drive, and the supervisor.

I hate to turn ideas down, I hope I don't come across as callous or flippant.  This just isn't the direction I'd like things to head toward.

Might I suggest giving [@samcauley's Google Drive addon](https://github.com/samccauley/addon-hassiogooglebackup/) a try?  It lets you sync any file in /share and /config specified by a file pattern to any folder in Google Drive.
