### ISSUE TITLE
UI doesn't support dark mode (0.114)

### ISSUE THREAD

**Issue by guice** [sabeechen/hassio-google-drive-backup#220]
In update 0.114, HA added a dark-mode option. In the past, dark themes never worked, but they were third party themes. Now, HA has an official dark-mode option, and the same thing happens:

<img width="1493" alt="Screen Shot 2020-08-14 at 11 51 08 AM" src="https://user-images.githubusercontent.com/205378/90278457-bbd97100-de24-11ea-9370-ce8bfce05e66.png">

Please add support for themes / dark-mode.

**Comment by sabeechen** [comment]
I agree this should do something better automatically, but in the meantime you can change the addon's background and accent color in the Addon's "Settings" > "Look and Feel"

**Comment by guice** [comment]
Hmm. I don't have a "Look and "Feel" option with the settings. I'm using 0.98.3.

**Comment by sabeechen** [comment]
You're using a pretty old version of the addon, you'll need to update.  Support for different color schemes was added in 0.99 and today I just released 0.101.  The version you're using is kind of broken with the recent theming changes, which is why you're seeing a black background with black text.
I looked into how themes are implemented in Home Assistant, and unfortunately even with the recent changes there still isn't a way for an addon to ask what theme or color pallette the Home Assistant interface is currently using (at least nto one I'm aware of).  For now giving the option to change the colors is what I can do.  If HA supports this in the future, I'd be happy to make it work wit the addon.

I'm closing this for now, but feel free to reopen it if there is something more I can help with.

**Comment by guice** [comment]
>  You're using a pretty old version of the addon, you'll need to update.

Oh, now I see. I never saw any updates - none. I did actually compare my version with your latest Release version here first, before submitting the ticket -- https://github.com/sabeechen/hassio-google-drive-backup/releases

Anyway, turns out I didn't see any updates because the repo. URL was removed at some point (somehow). Adding it back in, and I saw the update now. 

Updated, done. Thanks. I guess this will work. Hopefully HA will supply some way to pass-down the css into iframes here in the near future. I can submit a Feature Request....tomorrow.
