### ISSUE TITLE
Error recovering backups

### ISSUE THREAD

**Issue by patrul** [sabeechen/hassio-google-drive-backup#233]
I have had an issue with my HA installation and decided to start from scratch and use one of the recent backups but it has been imposible,

I have tried with all of available backups, with full and parcial recovery, and it shows the following errors:

```
20-08-23 12:34:27 INFO (MainThread) [supervisor.snapshots] Partial-Restore 0484ba1f start
20-08-23 12:34:39 INFO (SyncWorker_4) [supervisor.docker.interface] Stop homeassistant application
20-08-23 12:35:40 ERROR (MainThread) [supervisor.snapshots] Restore 0484ba1f error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 299, in do_restore_partial
    snapshot.restore_homeassistant()
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 463, in restore_homeassistant
    self.sys_homeassistant.refresh_token = self._decrypt_data(
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 208, in _decrypt_data
    data = padder.update(decrypt.update(b64decode(data))) + padder.finalize()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 145, in finalize
    result = _byte_unpadding_check(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

```

If I try to recover one addon, it says

```
20-08-23 12:17:00 INFO (MainThread) [supervisor.snapshots] Partial-Restore 77cae4e6 start
20-08-23 12:17:08 INFO (MainThread) [supervisor.snapshots] Restore 77cae4e6 run Repositories
20-08-23 12:17:09 INFO (MainThread) [supervisor.store] Load add-ons from store: 74 all - 0 new - 0 remove
20-08-23 12:17:09 INFO (MainThread) [supervisor.snapshots] Restore 77cae4e6 old add-ons
20-08-23 12:17:09 ERROR (MainThread) [supervisor.addons.addon] Can't read tarfile <supervisor.utils.tar.SecureTarFile object at 0xb0e47208>: not a gzip file
20-08-23 12:17:09 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't restore snapshot for 15ef4d2f_esphome
20-08-23 12:17:09 INFO (MainThread) [supervisor.snapshots] Partial-Restore 77cae4e6 done
```

What am I doing wrong? Any idea? I am really worried not being able to recover it

**Comment by sabeechen** [comment]
I don't think you're doing anything wrong, but just to be upfront its possible your snapshots might be unusable.  I'll provide any help I can.

The addon depends on the supervisor to do the actual work of creating and restoring snapshots.  This error indicates that the supervisor doesn't think that snapshots contain a valid compressed bytes.  The only thing I know of that could cause this is data corruption.  Some possible causes of this (note: just speculation):
- The supervisor has a bug somewhere in its snapshotting code.
- This addon has a bug that caused the backed up snapshots to be corrupted when they're copied to Google Drive.
- The snapshots were created on a corrupt disk (eg when the snapshot was read after creation, it wasn't what was written).

Its unlikely that this was caused by a bug in the supervisor or addon, because I'd expect to see a lot more issues get posted (but its always possible).  If the issue is disk corruption, this can cause a whole lot of strange problems (including this) and it might have been what prompted you to restore in the first place.

In terms of getting things up and running again:
- You might be able to do several partial restores, eg first do a partial restore of just "Home Assistant Configuration" and then each addon individually.  If only one part of the archive is corrupted (eg esphome in the logs you posted) then you might be able to restore everything else.   If it is just esphome with the problem, then you might be in luck because most of esphome's config is actually stored in the Home Assistant config folder. 
- You can try opening the snapshot in 7-zip (or another archive manager), since its just a regular compressed archive.  This woulnd't be a convenient way to restore, but at least you might be able to get at the most important config files.  One caveat is that if you protect your snapshots with a password, then you'll be able to open the snapshot archive but all of the files inside will be additionally encrypted and I'm not aware of any tool that lets you decrypt them.

For avoiding this in the future you might consider using the addon's [generational backups](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/GENERATIONAL_BACKUP.md).  Nothing will protect from every kind of failure, but this keeps older snapshots around for longer, so if for example corruption starts showing up down the road its more likely you'd have an older snapshot from back before the problem started.

**Comment by strangerting** [comment]
i've also just had this problem today on 104.4.  I made a minor config change to zigbee2mqtt and the whole box died and needed a fresh install - which itself is weird.  My setup is hass io onvtop of proxmox running over a mirrored ssd on ZFS.  I did a fresh install and then copied all backups (28 days worth) via samba from gdrive.  none worked.   I also tried to manually decompress various -  i can untar the latest backup but the .gz files inside appear corrupted. The earliest I have on gdrive from 113.3 so whatever it is its been around for a few weeks at least.

**Comment by strangerting** [comment]
-ok maybe not the same issue but my mistake!  It seems I may have been trying to use the wrong password my snapshot restores

@patrul - not sure if this might be the same issue for you?

**Comment by patrul** [comment]
I assumed if the supervisor starts the recovery task with the password filled in, it is the right password. If I use another one, supervisor logs an error

I started reinstalling and configuring it from scratch. I don't know where the problem was

**Comment by sabeechen** [comment]
I'm glad to hear your problem was a bad password, if I get more than one report of an issue I start to really worry I did something wrong :)

With respect to data corruption, its really awful because a bad SD card (or any kind of drive) can cause someone to have broken snapshots for a very long time and the only way to notice is when you go to restore.

I think I should be able to add some basic checksum verification once an snapshot is uploaded to Drive to verify that the bytes read and written are identical.  I might also be able to read a snapshot locally and very that its actually a parseable snapshot.  That woudl at least let someone get notified when corruption starts even though the addon can't do anything about it.

**Comment by sabeechen** [comment]
I've made a new feature request to do checksumming for the snapshots uploaded to Google Drive.  This won't catch all cases of data corruption, but should at least help some of them.  I'll try to get it into the next release.
#262
