### ISSUE TITLE
More Security - Allow App Passwords

### ISSUE THREAD

**Issue by IIAIronWolf** [sabeechen/hassio-google-drive-backup#240]
It would help me, and I'm sure many others, feel more safe about using this if the authentication process allowed users to use an app password that only works for this service, instead of having to authenticate with their entire Google account. 

However, this add-on works great and I very much appreciate all the work you have put into this thusfar!

**Comment by sabeechen** [comment]
IIUC, app passwords act as something like a "proxy" for your account login that can be revoked at a later date without changing your actual password.  They grant access to your whole account (or at least a whole Google product) and I think the way the addon works right now gives it much less privilege (eg more secure if something got compromised) on an account that uses it, I've explained a little bit about how that works below.  I couldn't tell from the Google's docs if app passwords works with Google Drive either, I think it might be a feature that predates Google's Oauth2 permission system.


Google Drive handles authentication with third parties (eg this addon) through Oauth2 [Scopes](https://developers.google.com/identity/protocols/oauth2/scopes).  The only scope the addon asks for is [drive.file](https://developers.google.com/identity/protocols/oauth2/scopes#drive) which is the most restrictive scope that also lets you create files in Drive (it can only see files/folders that the addon itself creates).


When you authenticate the addon with Google Drive, you should see a prompt that says something like this confirming that it has only that permission.  Its important to note that at this point you're logging in to Google's server, the addon never sees your Google account name or password.  The addon doesn't get access to anything else in Google Drive or any other part of your Google account:
![image](https://user-images.githubusercontent.com/21026774/91512152-8f027080-e89e-11ea-94f5-ad4e87800262.png)




As far as I know, this is the most restrictive way the addon could run (it _does_ have to upload files after all :), but if you know of a way to do it better I'd be all ears.  There are actually some useful features the addon can never have because I've chosen to use the most what I think are the most restrictive permissions, for example importing a snapshot into HA by uploading it into the snapshot folder in Google Drive.   You can verify what permission the addon has by going to your Google account page here (https://myaccount.google.com/permissions) and looking up up Hass.io Google Drive Backup (I know I need to update the name there, it should be "Home Assistant Google Drive Backup").

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think I missed something please feel free to reopen it.

**Comment by IIAIronWolf** [comment]
Thanks for the great explanation! That might be very useful to have in the README. I like it alot.
