### ISSUE TITLE
Problem starting this add-on

### ISSUE THREAD

**Issue by rabinshr** [sabeechen/hassio-google-drive-backup#249]
I installed your add-on but when starting it, I keep noticing an error in the system logs
![image](https://user-images.githubusercontent.com/1313863/91688042-6c28d280-eba4-11ea-83d4-1a5af2c5c0c2.png)

I checked this github repository and I don't see `0.101.2` tag, the last tag was `0.98.1` 🤔 
Any help is appreciated. This is exactly the add-on I wanted for backing my snapshots outside of local storage.

**Comment by sabeechen** [comment]
I've seen this happen sometimes from other users, I'm pretty confident its a problem in the supervisor.  I push new versions to DockerHub directly instead of releasing tags on GitHub, and [that tag is definitely there](https://hub.docker.com/repository/docker/sabeechen/hassio-google-drive-backup-aarch64).

I'd recommend uninstalling the addon, restarting the supervisor, then reinstalling the addon.  That seems to have worked for people in the past.

**Comment by sabeechen** [comment]
I'm closing this issue for now, but feel free to reopen it if there is more I can help with.
