### ISSUE TITLE
Old snapshots don't show up

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#258]
@hscheele reported in another bug that:

> They are, although I now have 3 different folders there based on the various installations since NOV 2019 (named "Hass.io Snapshots") and the recent ones yesterday and a few days before (each named "Home Assistant Snapshots"). But directing the add-on manually to the right one of them seems to work. But after that no former backups visible within add-on

And it can't be attributed to using a custom google api token.

**Comment by sabeechen** [comment]
Is it possible you used a different account before?  Older snapshots created with a different account won't be visible to a new one even if both accounts have permission to see the snapshots in Google Drive.

**Comment by hscheele** [comment]
No, definetly the same account as before. This happens also on a fresh install without log-in to this Google Account before. Also on a different computer in the same network. 

Can I do something to isolate the problem?

**Comment by hscheele** [comment]
Update: By 4 pm CET  something happened (probably with Google Drive) and the additional backup (from the former install) showed up without anything changed in between. In addition, the same snapshots view was opened within my browser since at least for 4 hours before and suddenly the former backup appeared and could be restored afterwards. Then, it was also showing up into "Supervisor" / "Create snapshot" where the file was not showing up, ebven when it was placed manually by using Samba share.  

Result: While still keeping in mind, that this is a one time effect is remains, that I cannot be sure that  I will be struggling again during the next backup (what will surely happen when using a Raspberry Pi).

**Comment by sabeechen** [comment]
Well I'm glad it resolved itself, but bummer that we probably won't be able to tell what went wrong.  If you run into any other trouble feel free to reopen this or make a new bug, I'm going to close this issue for now.
