### ISSUE TITLE
Template error.

### ISSUE THREAD

**Issue by romlisrl** [sabeechen/hassio-google-drive-backup#276]
Hello, I have a template error on HA server logs.
Running on Raspberry pi 3B with dockers containers.
Logs in attach.
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/5360650/home-assistant-google-drive-backup.log)
[HomeAssistant.log](https://github.com/sabeechen/hassio-google-drive-backup/files/5360651/HomeAssistant.log)

Thanks , might it be connected to google backup addon?

**Comment by sabeechen** [comment]
It is.  The problem is that when Home Assistant restarts the snapshot sensor doesn't exist until the addon publishes (sensors like this one don't get persisted across restarts).  Because the addon doesn't know when Home Assistant starts up or restarts, it just publishes on a schedule.
You should see the sensor come back within 5 minutes, at present I can't make it come back faster without really spamming the supervisor error log, which causes much more user frustration.
I suspect there is a better way for the addon to publish its sensors to avoid this problem, but so far I've been unable to find any resources that indicate how.  If anyone can point me toward that, please reopen this bug to let me know and I'll look into it.
