### ISSUE TITLE
use externall address or internal address:port for opening local snapshot folder

### ISSUE THREAD

**Issue by corchat** [sabeechen/hassio-google-drive-backup#278]
If I want to restore a snapshot I get redirected to the local snapshot folder of home assistant.
this is done using an url subdomain.domain.tld:port/hassio/snapshot
In home assistant i configured an external address of subdomain.domain.tld and an internal adderss ip:port
the redirect url should be either one of those addresses.

**Comment by sabeechen** [comment]
Yeah, I think I can do better than this.

The thing is, there are so many different ways for this to be configured and the addon can be accessed.
* Through ingress
* Through the "Extra server" port
* Through a reverse proxy
* Through path forwarding

The correct path to Home Assistant's snapshot page is different for each of these cases, and in various combinations.
At some point, I got it working halfway, and nobody complained.  Does anyone ever actually use this link, I wondered, instead of just making the two clicks to go there themselves?   I thought to myself... who cares?  This is good enough.

**But you care**, @corchat 
This is not good enough.  And for you, I will fix it.

**Comment by sabeechen** [comment]
I just released the addon version 0.102.0, which includes a fix for this.  Please let me know or reopen this issue if you run into any trouble with the new version.
Also just a reminder, to make Home Assistant see the new version right away go to "Supervisor" > "Add-on Store" > Three dots in the top right corner > "Reload"
