### ISSUE TITLE
WebUI formatting

### ISSUE THREAD

**Issue by habitoti** [sabeechen/hassio-google-drive-backup#303]
Just a tiny issue, but maybe worth polishing, as it looks rather broken right now. The WebUI doesn‘t properly use the available space to display the size of snapshots, e.g. when running on iPad in Hassio app (or according desktop sizes):

![D5618736-506D-4CED-9463-0869ECFD42F8](https://user-images.githubusercontent.com/220421/98333153-6adeb080-2000-11eb-9340-0da095c390c4.jpeg)

**Comment by sabeechen** [comment]
I think it there must be something else going on, because it renders correctly on my ipad mini 4.  
![image](https://user-images.githubusercontent.com/21026774/98395765-f6b10680-2019-11eb-8a5f-a47154c22477.png)
Might be some specific screen size that causes the problem.  Unfortunately the ipad doesn't give me many ways to test that.

Does the same thing happen if you open the interface through a browser?
What about portrait vs landscape orientation?

**Comment by habitoti** [comment]
You can easily simulate that with a desktop browser. Just shrink the width, and it just happens around the size that obviously also my iPad Pro falls into. When it gets even smaller, it's again ok, until it finally really has not sufficient space.
On my MAC Safari desktop, it's good between exactly 1099 - 1248 px width, and again from 1599px and wider. For all other widths, it breaks.

**Comment by sabeechen** [comment]
Figured it out, an errant css rule. I had to make the width of the text a little bigger to see it happen, but it will happen on any browser.  I'll fix it in the next update.

**Comment by jazzmonger** [comment]
I'm not sure if this is related however from time to time whoever you are I will not show top bar menu options unless I rotate my iPad to the horizontal position instead of landscape mode. It is a very intermittent problem and reloading Safari Or Chrome sometimes fixes it.

Pulling down on the window you can clearly see that all the controls are there But then they disappear. I sometimes have the same thing happen on the supervisor panel where I cannot see dashboard snapshots, etc. And I have to rotate from landscape to horizontal mode and/or reload the browser completely so this may be more of a home assistant general you are a problem than it is with your specific app.

![9B782207-4BD1-4C7B-9D74-8EA64E471A8C](https://user-images.githubusercontent.com/52110065/101259284-de95db00-36dc-11eb-80f9-b0e123fd1aab.jpeg)

**Comment by sabeechen** [comment]
I've fixed this in the latest version, 0.103.0.  Please let me know if you run into any more trouble with it.

**Comment by habitoti** [comment]
Looks good now, thanks!
