### ISSUE TITLE
Addon configuration page does not display with Firefox 82.0.2 (64-bit)

### ISSUE THREAD

**Issue by markcocker** [sabeechen/hassio-google-drive-backup#305]
Addon onboarding web page would not display on Firefox 82.0.2 (64-bit) on Mac, but works with Chrome 86.0.4240.193 (Official Build) (x86_64).

### Recreate
- burn hassio image onto 256MB SD card - image was downloaded from  [Installing Home Assistant OS](https://www.home-assistant.io/hassio/installation/) version 'Raspberry Pi 4 Model B (1 GB, 2 GB, 4 GB and 8 GB model) 64-bit (64-bit is required for 8 GB model)'
- boot image using Raspberry Pi 4
- Use Firefox 82.0.2 (64-bit) on Mac to connect to https://192.168.0.104:8123/
- Create new user
- Install and start this the addon
- Open addon web UI shows the title but no content

I could open the web UI using Chrome 86.0.4240.193 (Official Build) (x86_64).

**Comment by sabeechen** [comment]
- Male sure the add-on logs don't show any errors.
- Try loading the page with Firefox and then checking the supervisor logs ("Supervisor" > System" > "Logs").  If the problem is with the supervisor then some kind of error should show up there.
- Since the problem only happens with one browser, it could be that some browser extension (for example an ad blocker) in Firefox is interfering with the iframe that the supervisor loads the add-on Web UI in.  If possible try onening the UI with extensions disabled.
- If none of that works, open the Firefox console (Cmd + Shift + J) after trying to load the add-on web-ui, it might have an error message that illuminates what's going on.

**Comment by sabeechen** [comment]
Accidentally closure

**Comment by markcocker** [comment]
@sabeechen Thanks for the suggestions. I couldn't recreate by stopping and re-installing the addon, and I can't attempt to recreate from scratch as I don't have a spare SD card. I'll close for now, but will re-open with more detail if I can recreate in the future.
