### ISSUE TITLE
generational backup misbehaving?

### ISSUE THREAD

**Issue by capstan1** [sabeechen/hassio-google-drive-backup#31]
Hi, I think I ran into an issue.
I configured the configurational backup. (Thanks for the amazingly fast implementation btw!)

I used the following configuration:
```
{
  "max_snapshots_in_hassio": 3,
  "max_snapshots_in_google_drive": 30,
  "days_between_snapshots": 1,
  "use_ssl": false,
  "send_error_reports": true,
  "generational_days": 6,
  "generational_weeks": 3,
  "generational_months": 11,
  "generational_years": 10
}
```
While it started good (4th of april, next 11th of april), I afterwards still have all my daily backups in Google drive.
![image](https://user-images.githubusercontent.com/17147867/56888520-726ce300-6a74-11e9-9fc2-10cda9e0c928.png)
Shouldn't it delete everythung but 18th and 25th?

Or am I missunderstanding the behaviour? Does it start deleting only if it gets to the max limit? But then, why did it "work" at the beginning.

Clearly, it's no serious bug as no data is lost, I'm just wondering if something is wrong or I just don't understand.

**Comment by sabeechen** [comment]
Thanks for all the detail.  Bugs with detail are my favorite.   It'll only start deleting older snapshots once it hits your limit, which I admit is kind of confusing.  With your config I'd expect to see all your daily's kept until somewhere in the beginning of may, when it will start deleting older snapshots first that don't land on a monday or first of the month (or the closest snapshot to it) 

The only change I've made to generational backups since release on Apr 3rd was to fix a timezone conversion problem on Apr 11th.  That *could* be what caused the deletions earlier in the month, but even then with your configuration it should save weekly snapshots on a monday and monthly snapshots on the 1st of the month, which doesn't match 4-04 or 4-11.  Are you confident your settings weren't any different back then (it was a month ago after all)?

Separately, I gather it was confusing to you how generational snapshots work.  Not deleting older snapshots until Drive was "Full" seemed like the better idea to me since it lets you keep *more*, but I'm starting to think that might have been the wrong call.  It can be weeks or months before it *looks* like its working depending on the settings.  Maybe it would be better to just ignore the the max allowed in drive entirely in this situation and clean up prematurely.  I think it would be a good idea for me to beef up the documentation for generational backups at least, maybe make a separate page for it since the logic is actually kind of complicated under the hood.   I don't think I've hit the right balance of understandable vs helpful.  What do you think?

**Comment by capstan1** [comment]
I don't know, was generational backup evene released back then? Maybe it's just coincidence. (Or not that much coincidence - probably I hace chosen weekly backups before and changed to daily because of the new feature. Sadly I don't remember).
I'm not sure how to decide this. I would have expected to fill the limit up with a priority on the other settings (e.g here: always having 6 days, 3 weeks, 11 monthts and the rest with years). **However** this also would mean, that in some configurations one would never meet the max number. Additionally, more security is always better (obviously better than expecting that it is acting like it does now and seeing backups dissapear).

Independent on what you decide: both ways should be perfect, as long as you give a short explanation what will happen.

Thanks for your hard work!

**Comment by sabeechen** [comment]
Here's an option I hadn't thought of, I could just make it configurable.  Like add a checkbox for "Purge Generational Snapshots Early", where when you check it snapshots get cleaned up if they're not associated with one of the time-frames associated with a generational snapshot even if you have the space available in Google Drive.
That would have the added benefit of being "opt-in", so anyone that already had generational backups enabled wouldn't suddenly see their snapshots disappear when they update the add-on.

**Comment by capstan1** [comment]
Definitly a nice solution!
btw: Home Assistant really benefits of projects like these where the developer puts emphasis on the user interface and basic design and workflow decissions. Thanks a lot.

**Comment by sabeechen** [comment]
100% agree, generally I think its the project's biggest hurdle keeping it from going much, much more mainstream.

**Comment by sabeechen** [comment]
I was't able to get this into the latest release (v0.97) because it was already getting too big, but I'll work on making  this change in the next one.

**Comment by sabeechen** [comment]
Took me a loooong while to get to this, but I've added an option to "aggressively" clean up old snapshots with generational backup in v0.99.0.  You can check for it under "Partial snapshots" in the settings menu.
