### ISSUE TITLE
Delay new snapshots for a while (10 minutes?) right after startup

### ISSUE THREAD

**Issue by jds11111** [sabeechen/hassio-google-drive-backup#342]
Today I rebooted HassOS (in order to unplug it and move it), and it would not reboot properly.  No web UI and no SSH, but I could ping it.  The only way to reboot was to hook up a monitor and get the login prompt.  I logged in with 'root' and then it would continue booting fine. This was repeatable, so I thought that there was a problem and better make a backup.  That is when I discovered that there was an automated snapshot already taking place, and that was probably causing the reboot problem.  It makes sense that rebooting during a snapshot is a bad idea. 

I suppose that the easiest fix is to make a persistent notification during a snapshot that gets removed after finishing, to warn the admin not to reboot yet.  Ideally it would shutdown smoothly, but that seems more complicated.

**Comment by sabeechen** [comment]
What makes you think making the snapshot was causing the problem?  AFAIK making the snapshot just writes to a bunch of temp files until it completes, so if the system reboots mid snapshot it will just clean them up later.  I do this often on my machine(s) while testing the addon since as far as I know rebooting is the only way to make the supervisor stop a snapshot in progress.

Its worth noting that a snapshot can make the system very slow, since its disk and CPU heavy task (compression, writing, reading, etc).  This is very noticeable if you're using a raspberry pi with an SD card, and might explain the behavior you saw.

**Comment by jds11111** [comment]
Well, i was using an SSD on the RPi4. The behavior was reproducable. No matter how long i waited, i could not SSH into the machine. If i rebooted, it was still the same. Only after i hooked up the monitor on reboot, and logged in as root (a prompt that otherwise never shows up) did the web UI start immediately. I cannot be sure that it was the snapshot, but after i let it finish, it began behaving normally again. How could one be certain?

**Comment by sabeechen** [comment]
It would be hard to pin down the snapshot as the cause, this would be difficult to reproduce reliably.  The issue is that boot up is a very busy time for a computer, as a lot of expensive tasks can take place all at once.  For example if the supervisor has been off for a long time and then starts up it may decide to update a bunch of addons.  Many such tasks can take place all at once, which might cause the supervisor's web-server to be slow or unresponsive until there is less competition for disk/cpu.

What I think might be a good Quality of Life improvement for the addon is that if it detects you just booted up, have it wait a little while (maybe 10 minutes) before it starts any snapshots.  Then its less likely to compete with the Supervisor/HA for resources during start up.

**Comment by jds11111** [comment]
That does seem like a good idea.  But I am wondering if the problem happened during shutdown. Why would HassOS suddenly require a root login just to start up?  Anyway, like you say, it seems like it would be hard to track down exactly what happened.

**Comment by sabeechen** [comment]
It took me a longer than I hoped to release this feature, but v0.104.1 is available now with this functionality.
To update the addon, go to:
`Supervisor` > `Add-on Store` > Click the `...` in the top right > `Refresh`
and you should see the new version.

Kindly reopen this bug and let me know if you continue to run into problems after updating.

**Comment by jds11111** [comment]
Great! Thanks!
