### ISSUE TITLE
Problem with filenames tar files

### ISSUE THREAD

**Issue by MarcelJ28** [sabeechen/hassio-google-drive-backup#350]
Hi,

When the add-on makes a tar file it is named for example Full Snapshot 2021-02-12 23:00:00.tar And it will go right in Google Drive. But I have an automatic sync from Google drive to my Synology NAS and I noticed that the files were not on my NAS although they are on my Google Drive. When I downloaded them by hand I noticed the name was changed to Full Snapshot 2021-02-12 23_00_00.tar. So I think the sync to my NAS does not work because of the 23:00:00. Can that be changed to something else?

**Comment by sabeechen** [comment]
In the addon settings (click "SETTINGS" at the top of the page in the add-on UI)  you can change the snapshot name.  You can see [here](https://github.com/sabeechen/hassio-google-drive-backup#can-i-give-snapshots-a-different-name) for a list of what kind of tokens you can use in the snapshot name.  For example if you wanted to replace the `:` with `-` you could use a name like:
```
{type} Snapshot {year}-{month}-{day} {hr24}-{min}-{sec}
```

Note: lots of users are having lots of problems with running this addon on Synology NAS, which seems to be because Synology is not supported by the HA Supervisor.  I've heard that some have had success by running HA on a VM on Synology instead.

**Comment by MarcelJ28** [comment]
Thanks. Sometimes the solution is simple. 😉

And no I am not running Home assistant on my Synology. But I sync my Google
drive to my Synology. And that will work fine now with this change.

Op za 20 feb. 2021 17:34 schreef Stephen Beechen <notifications@github.com>:
