### ISSUE TITLE
backup seems to periodically crash

### ISSUE THREAD

**Issue by magiva** [sabeechen/hassio-google-drive-backup#355]
i get notified every few hours that my hassio has restarted, when i check the logs i see this

21-03-03 12:32:30 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup

21-03-03 12:55:39 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-03 12:55:39 INFO (MainThread) [supervisor.resolution.check] System checks complete

with the blank lines between also... no idea why that is.

if i can provide more information then just ask.

**Comment by sabeechen** [comment]
Those are normal log messages for correct functioning of the addon, its just checking for new snapshots with the supervisor once/hour and that check is very unlikely to cause a system crash.  The steps below should help determine if the problem is actually with the addon:

Depending on how you have your machine configured, this might be difficult to troubleshoot.  Home Assistant goes through some effort to abstract users away from the underlying hardware, and this problem is most likely in the underlying hardware 
- Could I have you post the contents of going to "Actions" > "Report a bug" from within the addon UI?  This will help speed things up as I won't have to ask a bunch of questions about what kind of setup and configuration you have.
- If you haven't tried already, turn off the addon, reboot the machine (in that order) and wait for a while to ensure its actually the addon causing the reboots.
- There is probably something in the supervisor logs ("Supervisor" > "System") that will indicate what the problem is, but I don't think the supervisor logs get persisted after a system crash so it might be hard to find anything there.
- While the addon is off, try making a snapshot through the supervisor ("Supervisor" > "Snapshots").  If you see the same reboot behavior then the addon is definitely not to blame.  Some things it might be if you still see the reboot in this case:
  - Hard Drive or SD card is out of space
  - Corrupted Hard Drive/SD Card
  - Not getting enough power (eg if you're running this on a raspberry pi with a low-power adapter)
 -  If you have ssh access to the host machine (the actual host, not one of the ssh addons) its possible the command ```last reboot``` could give you information about why the machine last restarted.

**Comment by magiva** [comment]
i re-installed from a different repo
https://github.com/sabeechen/hassio-google-drive-backup

and it seems better

**Comment by sabeechen** [comment]
Alright, if you think I can help more, feel free to reopen the issue.
