### ISSUE TITLE
Have my backup a normal behaviour?

### ISSUE THREAD

**Issue by IsaTTeN** [sabeechen/hassio-google-drive-backup#36]
Hi there!

I´m testing this amazing add-on, everything seems its working but I have a doubt:

When I make a backup, direct or schedulled, that backup doesn´t upload to google drive when the snapshot is finished in local. I have to wait till next schedulled backup. In other words, the last backup doesn´t go to Google Drive ultil next day.

If I press the Sync button the last backup starts to upload inmediatly to Google Drive, so the sync process it´s working but for some reason when the last backup finish, the add-on is unable to trigger the sync to Google Drive. It remains in state pending

![image](https://user-images.githubusercontent.com/20249994/57039129-b5d17800-6c53-11e9-976f-8c3e9a03ed97.png)

Is this normal???

Best regards

**Comment by sabeechen** [comment]
I think I know what's causing this, it has to do with how the addon notices changes in the backup directory.  If I'm right, then you should see the addon notice the snapshot is finished and upload it within an hour even if you don't sync manually.  Definitely not *correct* but it should resolve eventually.

I'll make a fix for the next release.

**Comment by IsaTTeN** [comment]
Finally the file uploaded automaticaly to Gdrive without doing a manual Sync. In the log I can see this:

2019-05-01 20:32:01,300 INFO Backup directory has changed
 and 1 Hoy after:
2019-05-01 21:32:05,948 INFO Uploading Full Snapshot 2019-05-01 19:30 HA0.92.1
2019-05-01 21:33:16,352 INFO Upload complete

It´s like 1 hour of delay from the end of the snpshot until the upload

**Comment by sabeechen** [comment]
Yeah, that looks like what I suspected.  The issue is that I have the add-on watch for new files in the /backup directory to notice when a snapshot is complete, but often times the snapshot file shows up before Hassio has completed writing it (probably takes a while to write if its large) so the addon doesn't know to check for new snapshots again for a while.   I'll have it check to see if the last modified or file size has changed too so it can pick up when the writing is finished.

Thankfully it doesn't cause any data loss, it just takes longer to upload than it should.

**Comment by sabeechen** [comment]
I just released v0.94, which makes this change.  It now depends on the linux kernel to tell it when files have changed, which is what I really should have been doing in the first place.  With this update you should see the add-on notice when a new backup has been created and start uploading it within 5-10 seconds.  Feel free to reopen the issue if you still see it misbehaving after the update.

**Comment by IsaTTeN** [comment]
Tested and it works like a charm!!!!

Good Job!!!

Thanks alot for your effort and quick response

Best regards
