### ISSUE TITLE
Feature Request: Decrypt snapsots

### ISSUE THREAD

**Issue by zeeuk** [sabeechen/hassio-google-drive-backup#367]
Once snapshots are encrypted would be nice to have an option to decrypt them without going to a full restore inside home assistant

Thanks!

**Comment by sabeechen** [comment]
Id like this too, I'm not sure if I could implement it in a reliable way but I'll look into it for a future release.  It might be better to make a separate tool for this that runs on the desktop.

**Comment by amandel** [comment]
1st thanks for your great add-on!

I was wondering about that too. Actually I had expected that a well known algorithm for encryption is used, so that the archive can be opened with any other standard tool on a different system (in my case 7zip on my desktop). I assume since the backups are created by the supervisor, this would be a feature request to the supervisor? Or could you run a final encrypting zip (AES) over the archive instead?

**Comment by sabeechen** [comment]
I've hacked together a separate command-line tool for decrypting backups [here](https://github.com/sabeechen/decrypt-ha-backup).  Its nothing fancy but I think it gets the job done, let me know if you run into trouble with it.

I don't plan to integrate this functionality into the add-on, from a maintainability perspective it would be difficult to make this part of the web-ui.  You could try bringing the issue up with the supervisor developers but.... I honestly I don't think there's a good chance they'd do it.  Though if enough people complain I bet we could get them to use a "standard" encryption method.

**Comment by amandel** [comment]
Thanks for your support and the tool. I've posted https://community.home-assistant.io/t/use-more-common-way-to-encrypt-backups/440376 lets see if it is picked up.
