### ISSUE TITLE
Feature Request: File upload service

### ISSUE THREAD

**Issue by xbaro** [sabeechen/hassio-google-drive-backup#377]
First of all, congrats for this great job. I was wondering if it will be possible to add a service to send a file to GDrive?  It could be really useful in order to backup only certain files when some event is detected.

Thanks.

**Comment by lbouriez** [comment]
https://github.com/sabeechen/hassio-google-drive-backup/issues/354

**Comment by xbaro** [comment]
This thread is about other storage services, therefore is not the same. My question was if it is possible to add a Home Assistant service that you can call with a path and it uploads this path to the Google Drive, which is something this code is doing, so do not need extra packages.

**Comment by lbouriez** [comment]
My bad

**Comment by sabeechen** [comment]
At this time, I'm not considering making this addon do anything except upload snapshots to Google Drive.  My main reason is that I have to keep the feature set pretty focused in order to deliver something high quality but also maintainable.

You guys might want to check out [this addon](https://github.com/samccauley/addon-hassiogooglebackup) which also backs things up to Google Drive.  It isn't as easy to set up, but offers more flexibility wrt which files and folders you might want to back up.
