### ISSUE TITLE
Google Drive Backup doesn't start on Synology / Docker

### ISSUE THREAD

**Issue by Ruud2702** [sabeechen/hassio-google-drive-backup#380]
Hello,

i'm using Home Assistsant on a  Synology DS with Docker. Since the last Google Drive Backup-update the addon doen't start.
Can anyone help me, please?

21-04-10 09:32:10 ERROR (SyncWorker_5) [supervisor.docker] Can't start addon_cebe7a76_hassio_google_drive_backup: 500 Server Error for http+docker://localhost/v1.39/containers/cdcc6777dac55de052546e1fecfbca856b760c4338be17f578c847d1b261ffba/start: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

**Comment by sabeechen** [comment]
This is almost certainly because synology is using an older version of docker, which I believe is the reason that Supervised HA is "officially" unsupported on synology.  You can see [this thread](https://github.com/sabeechen/hassio-google-drive-backup/issues/339#issuecomment-782881054) for a little more context.

Unfortunately there isn't anything I can do about this, the problem is incompatibility between HA's supervisor and the docker version synology uses.
Duplicate #339
