### ISSUE TITLE
Backup progress bar

### ISSUE THREAD

**Issue by gwalker88** [sabeechen/hassio-google-drive-backup#381]
I would like to have more "live" status/progress info like a % complete progress bar.

**Comment by sabeechen** [comment]
Unfortunately the supervisor is what actually creates the snapshot, and it doesn't give visibility into how much progress its making.  In order to make this happen I'd need support for it in the supervisor first, which is out of my hands.

If you think there is anything else I can help with, feel free to reopen this bug and I'll do what I can.
