### ISSUE TITLE
BrokenPipe Error

### ISSUE THREAD

**Issue by AJax2012** [sabeechen/hassio-google-drive-backup#396]
Not entirely sure what this means, but I can't upload my most recent full snapshot of home assistant. 

Steps to recreate:

1. Open Snapshots addon in HA (running in docker container on Ubuntu Server 20.04.2 LTS. I know this version isn't officially supported, but I haven't really had any problems with it yet. If this is the problem, let me know and I'll resolve this issue.)
2. Select snapshot I wish to restore
3. Select Upload Snapshot

It fails at about 27%. Here is the error stacktrace. Please let me know if you have any questions.

```
05-06 00:40:08 DEBUG Making Hassio request: http://hassio/snapshots/new/upload
05-06 00:40:18 ERROR    
Traceback (most recent call last):   
  File "/app/backup/hasource.py", line 207, in save   
    resp = self.harequests.upload(stream)   
  File "/app/backup/harequests.py", line 41, in upload   
    return self._postHassioData(url, data=stream)   
  File "/app/backup/harequests.py", line 136, in _postHassioData   
    return self._validateHassioReply(self._client.post(url, headers=self._getHassioHeaders(), json=json, data=data))   
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 116, in post   
    return request('post', url, data=data, json=json, **kwargs)   
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request   
    return session.request(method=method, url=url, **kwargs)   
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request   
    resp = self.send(prep, **send_kwargs)   
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send   
    r = adapter.send(request, **kwargs)   
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send   
    raise ConnectionError(err, request=request)   
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))  
```

**Comment by sabeechen** [comment]
For some context this error is happening while the addon is trying to send the bytes of a snapshot to Home Assistant's Supervisor.  I've tried to make this more reliable, but for reasons I've never gotten to the bottom of Home Assistant's Supervisor runs into problems handling very long lived connections like the one thats necessary to transfer over a large snapshot.  Since ti doesn't have a mechanism to resume after a partial upload the only option for a failure like this is for the addon to start over from the beginning.

Since the snapshot you have in Google Drive is "just like any other snapshot" you don't actually need to use the addon to upload it.  You'll just need to get it into the <kbd>/backup</kbd> folder in Home Assistant to restore it.  Here are the most common ways of doing that:
- Install the Official Samba Addon and just copy it over using Samba.  Make sure you refresh Home Assistant's cache of snapshots by going to <kbd>Supervisor</kbd> > <kbd>Snapshots</kbd>><kbd>...</kbd>><kbd>Reload</kbd>.  This is what most people in your situation would do.
- Upload the snapshots thorugh Home Assistant's Web UI by going to <kbd>Supervisor</kbd> > <kbd>Snapshots</kbd>><kbd>...</kbd>><kbd>Upload</kbd>.  You are likely to run into the same problem here if you have a large snapshot, since this basically uploads the snapshot through the same API the addon uses.
- If you have access to the host machine's file system, copy the snapshot into <kbd>/usr/share/hassio/backup</kbd>, and then reload as above.
- You are running a relatively old version of the addon.  If you update it there is reason to think the new version will handle the upload better if you just try it again.  If you still have problems, you can go to <kbd>Actions</kbd> > <kbd>Report a Bug</kbd> and copy the output here, there is a small chance that could help me debug the problem further.

Once the snapshot is in the backup folder you can restore it through the Supervisor's snapshots page.

**Comment by AJax2012** [comment]
I can do that. I had issues trying to download it from Google Drive and install it directly from the supervisor/snapshots page as well, but I'll give samba a try the next time I need to restore a backup. I'll close the issue then. Thank you!
