### ISSUE TITLE
Feature request - configure output directory name  

### ISSUE THREAD

**Issue by ChrisSutton123** [sabeechen/hassio-google-drive-backup#406]
Very useful addon. Works great.
I have two HA installations, is it possible to have an option to specify the google drive output directory name for each installation?
Thanks

Found a workaround I can simply rename the folder in Google Drive

**Comment by sabeechen** [comment]
You can also choose the folder you'd like to use from the "Settings" UI within the addon, under the heading "Manually specify the snapshot folder".  It takes you to a page on [habackup.io](https://habackup.io) that lets you pick the folder you'd like to use in Google Drive, or you can paste the Drive-ID of the folder you'd like to use.  Using the website is recommended but not required.

But as you noted you can just modify the name of the folder it creates automatically too.  I'm not going to add an option to change the name of the "automatically" created folder, since I'd prefer for someone to choose their own folder right after installation if they want that kind of customization.
