### ISSUE TITLE
Snapshot temporary file location

### ISSUE THREAD

**Issue by LeChuck2909** [sabeechen/hassio-google-drive-backup#424]
Hi,

where is the location of the snapshots while being created ?

For whatever reason (maybe due to an update), the addon also included the media folder, and therefore not even one further snapshot could have been created, due to full disk.

The process of taking the snapshot was ongoing in a somewhat freezed situation. Therefore i aborted it and now i do not see an unfinished snapshot in the folder, but the disk is still full. so in need to find the temporary file location of the unfinished snapshot to remove it.

THX!

BR

**Comment by sabeechen** [comment]
The supervisor creates the snapshots, which is part of the Home Assistant installation (not the addon).  To the best of my knowledge the supervisor creates the temporary files for a snapshot inside the /tmp directory of its docker container, though I have not verified this myself.  I think that if you restart the host machine, the supervisor's docker container will get restarted and the temporary files will get cleaned up.  If that doesn't work, let me know and I can recommend some other (much more difficult) ways to clean up temp files.  Make sure you also delete any large snapshots it might have created with the media folder (assuming you already have them backed up or don't need them).

**Comment by LeChuck2909** [comment]
So i rebooted it several times ... i also removed some big files from my media folder to get back some free space at all and restarted the snapshot (still not knowing, that the snapshot include media folder and will again fill disk) and the snapshot again filled up my disk.

so there have to be several unfinished files. i use HA with HA OS on my raspberry pi 4. i will backup my media folder and flash my home assistant ssd, but i guess it would be interested where these files are, to avoid flashing in the future

**Comment by sabeechen** [comment]
The way HA OS is designed would make answering this question difficult.  For the most part it doesn't give you access to the host machine, just the docker containers running HA/Supervisor/addons/etc.  This can make figuring out whats going wrong with the hardware diffcult or impossible.  In theory its a relativelystateless OS so restarting should reset everything to back to the installation conditions (minus what you have in the /media, /config, /backup, /ssl, and /share directories) but I'm not even sure if there is any way to ssh into to host machine to muck around and verify that.

Since this isn't really a problem with the addon I'm going to close this issue, but if you think there is something I can help with feel free to reopen it and I'll do what I can.

**Comment by LeChuck2909** [comment]
ok, so i flashed my ha ssd back then and since then everything is working perfeclty fine again. the only thing which chould probably be interesting for your addon is, why the snapshot settings of the addon changed from excluding media to including media with one of the addon updates.

**Comment by sabeechen** [comment]
You ask a question that is hard to answer, so forgive me for a long response.  Its probably more detail than you want, but being upfront and honest with my users about the design decision I make with the addon is important to me and something I really think more developers should do.

The media folder was introduced to Home Assistant after the this addon was released, so I needed to update the addon to support it.  The way the feature was implemented in the Supervisor, anyone making a "Full" snapshot would have the media folder included in future snapshots because a full snapshot automatically includes anything it can.  However anyone making partial snapshots would have a change in behavior when they update the addon with my code changes.  I could have implemented it in two ways:

1. Automatically include the /media folder in partial snapshots once the addon is updated.
2. Automatically exclude the /media folder in partial snapshots once the addon is updated.

Because the addon keeps a list of folders it should *exclude* in its settings rather than a list it should *include*, going with option 2 would have meant I'd need to update the addon's settings on an upgrade to indicate that it shouldn't backup the /media folder.  Updating settings in the addon setting without the user's intervention is soemthign I generally try to avoid.  Additionally, because of how addons work in Home Assistant it was very difficult for the addon to know reliably whether its a fresh installation or an upgrade that previously created partial snapshots without the /media folder in them.

Because of these complications I opted to simply go with option 1 and note the addition of the feature in the changelog, hoping that it wouldn't inconvenience too many people to suddenly have it included.

Since then I've added some additional data gathering to the addon, so in in the future when it gets upgraded it can take note at start up that its version has changed and do some smart things depending on what functionality has changed from one version to the next.  For example if a change like the /media folder addition happened now, I could note the version changed, check if partial snapshots hadn't been backed up before and display a notification asking the user if they want to have the folder included.  It wasn't possible for the addon to *reliably* determine this back when the feature was added.

In any case I apologize that the way I supported the /media folder caused complications for you, its not my intention.  I'm often forced to make decisions in developing this addon that balance time, effort, and convenience in ways that trade one for the other.  Its my intention to make something that "just works well" but that goal isn't always possible in all cases, and in this case you suffered for it.  I know very well how frustrating it is when a Home automation server suddenly dies, especially when something like this addon is *supposed to make it more reliable*.  Its something I think about a lot in how I develop this project.

**Comment by LeChuck2909** [comment]
Ok, wow so thx for the honest and detailed answer. although i think there is no apology necessary ... at least for me. i am glad that this addon exists and you put your time into creating it. it is really one of the useful ones. and hey, dealing with open source things one have to take some fixing into account. im rather thankful for so many people like you participating in this things thant complaining about it.
