### ISSUE TITLE
Can't exclude media folder

### ISSUE THREAD

**Issue by dkliszewski** [sabeechen/hassio-google-drive-backup#442]
I tried to exclude folder "media" from snapshot, but when i'm trying to save settings, I get response:
Nie udało się zapisać konfiguracji dodatku, does not match regular expression. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 2, 'days_between_snapshots': 3, 'snapshot_time_of_day': '03:00', 'send_error_reports': True, 'use_ssl': False, 'accent_color': '', 'exclude_folders': 'media'}

Home Assistant Core 2021.8.1

What i'm doing wrong?

**Comment by sabeechen** [comment]
When you use the config editor in home assistant, it will sometimes add in the empty string for configuration options that shouldn't be empty.  Its something I have [strong opinions on](https://github.com/home-assistant/frontend/issues/8364) but is unlikely to change.

It this case, it is complaining that 'accent_color' is empty.  If you remove that config option it should save correctly.  In the future I'd recommend using the setting dialog within the addon's web-ui, since it handles validation of things like this accurately.

**Comment by sabeechen** [comment]
In the latest release (v0.105.1) I've allowed the empty string for the accent color, which the addon interprets as "use the default color".

Please feel free to re-open this issue if you think there is something else I can help with.
