### ISSUE TITLE
Add on not found in add-on-store

### ISSUE THREAD

**Issue by doubledutch2** [sabeechen/hassio-google-drive-backup#448]
I added the URL https://github.com/sabeechen/hassio-google-drive-backup to my HA Addon store but the add on does not show up. Even rebooted HA and made no difference.

**Comment by sabeechen** [comment]
Try removing the addon repository and then adding it back.  If it still doesn't show up, check the supervisor logs (Go to ```Supervisor``` > ```System```).  If there are any problems they're likely to show up as an error in the sueprvisor logs.

**Comment by sabeechen** [comment]
Hrm it looks to be loading in fine.  That is exactly the output I'd expect and it is clearly saying the repo got loaded in.

This might sounds silly, but have you tried refreshing the page (with the browser refresh button) and scrolling to the bottom?  Sometimes HA caches things to aggressively, and I myself once though the repo wasn't getting added because it shows up off-screen underneath all the community addons.

This *shouldn't* matter, but also make sure you have "Advanced Mode" turned on for your user in Home Assistant.

**Comment by doubledutch2** [comment]
Hi @sabeechen - It was indeed caching! Used a different browser and it now shows up. Apologies for bothering you.

**Comment by sabeechen** [comment]
No worries, glad I could help.
