### ISSUE TITLE
Error while saving options

### ISSUE THREAD

**Issue by engi** [sabeechen/hassio-google-drive-backup#456]
Hi,

I'm using addon version 0.104.3 and HomeAssistant 2021.8.8.
When I try to save settings through the HA Supervisor Configuration tab, if [Show unused optional configuration options] button is OFF, all is ok, but if button is ON, I have an error message and options are not saved.

Error message is :
`Failed to save add-on configuration, does not match regular expression. Got {'max_snapshots_in_hassio': 8, 'max_snapshots_in_google_drive': 24, 'days_between_snapshots': 1, 'ignore_other_snapshots': True, 'snapshot_password': 'mypwd', 'send_error_reports': False, 'generational_days': 3, 'generational_weeks': 4, 'generational_months': 12, 'generational_years': 5, 'use_ssl': False, 'accent_color': ''}`

**Comment by sabeechen** [comment]
The supervisor's addon config screen has a bug when an addon, such as this one, has a *string value* config option that can't be the empty string.  In this case the problem is ```accent_color```, which should be of the form "#FFFFFF" or similar but the supervisor's config screen fills in the empty string ```''``` by default.

[I have strong opinions on this](https://github.com/home-assistant/frontend/issues/8364), but I don't think its going to get fixed.

The solution is to remove the empty config option, or to use the addon's web-ui itself to edit the settings.
