### ISSUE TITLE
How to decrypt in the desktop a encrypted backup?

### ISSUE THREAD

**Issue by opep** [sabeechen/hassio-google-drive-backup#461]
It may be a very simple question, but I could not do it. Maybe it can only be done by the addon, I don't know.
Fact is that I got in trouble in my HA configuration, having no access to Supervisor. I have the password that used in Addon to encrypt the backup, but found no way to decrypt it ouside of it.
Can it be done? Using WinRAR.
Thanks in advance.

**Comment by sabeechen** [comment]
My official stance on it is [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/210) but to sum it up I don't think its possible to open with any off-the-shelf tools.  Just in case you didn't know, the supervisor (eg Home Assistant) is the one that actually creates the snapshot. The addon just asks the supervisor to create the snapshot with/without a password.  I'm still not in a place where I could take on writing a decryption tool, but I'd encourage anyone reading this to consider contributing one to the supervisor codebase because I don't think it would be very complicated.

If you want to get just a handful of files out of an encrypted snapshot I think the only way is to restore it to a running Home Assistant instance and use that to get at them.  This is a lot of work and I agree, its kind of silly just to get some files.  If I were in your shoes and didn't have an unused raspberry pi that I could use to set up a new install, I'd install Home Assistant on a VM using [these instructions](https://www.home-assistant.io/installation/windows/).  You can install virtualbox for free.

**Comment by opep** [comment]
Thanks for your answer. That's what I was afraid. For the sake of a better future, I will consider not to encrypt it anymore, even it it is against my peace of mind using cloud servers. Luckily, I am not totally stuck, I have access to configuration using samba, but I will have to change a lot of files, but I whing is going to be easier than configure a new environment. Thanks for you clarification and hope someone could engage with a decryption tool. I believe it is pretty important to deal with encrypted files ouside of the system.

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but please feel free to re-open it if you think there is something else I can help with.
