### ISSUE TITLE
Snapshots is renamed to Backups in Home Assistant

### ISSUE THREAD

**Issue by johanf85** [sabeechen/hassio-google-drive-backup#465]
Recently there has been a change in using the name Snapshots. It is no longer in use and has been renamed to Backups. 

See: https://www.home-assistant.io/blog/2021/08/24/supervisor-update/

**Comment by PaperLawyer** [comment]
Yes, and a problem for many add-ons.  For example, my log this morning:

21-09-08 08:06:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of APC UPS Daemon
21-09-08 08:06:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome
21-09-08 08:06:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-09-08 08:06:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home
21-09-08 08:06:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of APC UPS Daemon
21-09-08 08:06:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome
21-09-08 08:06:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-09-08 08:06:40 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home

**Comment by sabeechen** [comment]
I've changed this in the most recent release (v0.105.X).  All references to snapshot have been renamed to backup in:
-  The web-ui
- The codebase
- Addon configuration options
- Sensors the addon publishes

Noteably when you update, the addon will automatically change its own configuration to use the new configuration values (eg ```max_backups_in_ha``` instead of ```max_snapshots_in_ha```).  The web-ui will also ask if you want the sensors the addon publishes to Home Assistant to use new names and values that reference backup instead of snapshot, just to make sure it doesn't break any automations you have using those values without your understanding.
