### ISSUE TITLE
Snapshot_backup sensor not available every hassio restart

### ISSUE THREAD

**Issue by damiano75** [sabeechen/hassio-google-drive-backup#47]
Hi,
after every hassio restart the sensor.snapshot_backup is not available and I need to manually restart the add-on

hassio 0.92.2
Hass.io Google Drive Backup 0.96.1

**Comment by sabeechen** [comment]
Home Assistant doesn't persist sensors published through he API across restarts, which how this addon publishes them.  You should see the sensor come back automatically within an hour or if you manually sync.  In a near update, I'll add some logic that narrows that down to a few minutes instead.

The issue is that Hassio doesn't provide addons a clean way to know if Home Assistant is up or down (eg when restarting) so its kind of a mess to sort out.

**Comment by sabeechen** [comment]
I've added this functionality to the just released v0.97
