### ISSUE TITLE
Exlude subfolders

### ISSUE THREAD

**Issue by bafplus** [sabeechen/hassio-google-drive-backup#476]
Its already possible to exclude some folders like /media and /share.
Would be great to be able to go a bit deeper.

Ex: I run Frigate and it stores the video files in /media/frigate.
That folder is about 20gb in size.
I can only exclude the /media folder but there are files in that folder that i do want to backup.

**Comment by sabeechen** [comment]
I'm unable to implement this in the addon because [it is a Home Assistant Supervisor limitation](https://github.com/sabeechen/hassio-google-drive-backup#can-i-exclude-specific-sub-folders-from-my-backup).

You might consider making a feature request in the [Home Assistant Feature Request forums](https://community.home-assistant.io/c/feature-requests/13).  If home assistant supported this I would also support it in the addon.
