### ISSUE TITLE
ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#51]
Hi, all seams working here, but I found this hassio log message.
Maybe it isn't a problem, but do you have some hints on how I can debug it?
Thanks,
Piero

**Comment by sabeechen** [comment]
Does it only show up while Home Assistant is restarting?  You can expect to see some errors in the supervisor log when Home Assistant is restarting, since Hassio manages the proxy that lets the add-on talk to Home Assistant to publish this sensor and it can't do that while Home Assistant is down.  Do you see anything in the add-on's logs?

**Comment by PieBru** [comment]
The error mssage shows after each computer reboot, btw it's an i7 with 8GB RAM, 1TB SSD and a minimal Arch Linux, so computer speed and resources shouldn't be an issue. I'm testing with only a minimal set of the installed hassio addons enabled.

Here is the boot hassio system log: https://pastebin.com/JvE84wjU
and the corresponding addon log: https://pastebin.com/u67T0n68

Reloading hassio core does not show interesting logs, but restarting hassio shows the error in the log appended:

`19-05-16 08:55:30 INFO (SyncWorker_11) [hassio.docker.interface] Restart homeassistant/qemux86-64-homeassistant

19-05-16 08:55:36 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]

19-05-16 08:55:36 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale

19-05-16 08:55:46 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
`

I'm new here and I'm not able to figure out what's going on.
Thanks for the addon and for the help,
Piero

**Comment by sabeechen** [comment]
I don't see any problems in the logs, the reason that error shows up is because the add-on is asking Hassio to send a request to Home Assistant, but Hassio can't because HA is restarting.  Hassio doesn't give the add-on a way to see if HA is restarting, so the only way to check is by printing such an error.  I'm hoping in a future version they'll give me a way to do that, because I've had a lot of people complain about this error message.

**Comment by PieBru** [comment]
Hopefully other people having this problem should find your explanation thanks to this issue title.
Thank you.
Piero
