### ISSUE TITLE
"Invalid Add-on repository!" when adding the repository

### ISSUE THREAD

**Issue by vadimbz** [sabeechen/hassio-google-drive-backup#527]
Repository is no longer addable from Addon Store > Repositories in latest version of Home Assistant Supervised

**Comment by SteffanH** [comment]
The error message in HACS when adding the repository is 
'Repostitory [sic] structure for v0.105.1 is not compliant'

Versions:
Supervisor: 2021.10.8
HA Core: 2021.11.5
Frontend: 20211109.0
HACS: 1.18.0

**Comment by koldk** [comment]
Same error 

ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (175 bytes)
POST git-upload-pack (244 bytes)
error: unable to write file /data/addons/git/cebe7a76/.git/objects/pack/pack-7439c2943a95c2eec9946ed6dc5002a28b9316a5.pack: No such file or directory
fatal: cannot store pack file
fatal: fetch-pack: invalid index-pack output
'.

**Comment by sabeechen** [comment]
No worries @vadimbz, people make that mistake [literally all the time](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=is%3Aissue+%22Repostitory+structure%22+), I just wish I had a way to make it clearer.

@koldk 
First some context:  Home Assistant uses git to download this addon's repository when you add it to the addon store.  The error you're seeing is from the git command line tools.  I've had [users report this in the past](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=is%3Aissue+%22Can%27t+clone%22+), and we've never been able to get to the bottom of why it happens.  It looks like its either a bug in Git or a problem in how Home Assistant uses Git.  There isn't currently anything I can do about it as an addon developer. 

Others have had success trying the following:
- Restarting the machine running Home Assistant (I suspect this clears out some temporary files that are jamming thing up)
- Attempting to add the repo over and over.
