### ISSUE TITLE
(Feature) Create template repository for google authentication

### ISSUE THREAD

**Issue by MrDonkey07** [sabeechen/hassio-google-drive-backup#531]
This project has a very robust and mature structure for Google OAuth authentication.

Could the core authentication functionality be templated and moved into a separate repository that could serve as a base for other addon projects using Google apis?

**Comment by sabeechen** [comment]
It could, but it would be a rather complicated project to write a library that handles all the different use cases, which isn't something I have the bandwidth to take on presently.  This project also only works well because it has a publicly hosted website ([https://habackup.io](https://habackup.io)) that generates the refresh tokens from Google, which is one of the things Google requires to use its API.  This currently is funded by donations, but my funding model wouldn't survive hosting a general purpose service for other projects.  I suspect doing so would also violate Google's developer terms of use (not 100% sure though).

If you're looking for pointers on how to implement such authentication on a project yourself, Google's docs are actually [pretty good](https://developers.google.com/identity/protocols/oauth2/web-server#python_1), though its also just a standard Oauth2 workflow.  The code where the addon handles this is [here](https://github.com/sabeechen/hassio-google-drive-backup/tree/master/hassio-google-drive-backup/backup/creds), though the only reason I wrote code to do it is because I couldn't find a non-blocking python Oauth2 library.
