### ISSUE TITLE
Enhancements: recover SQlite space and cancel pending/upload snapshot

### ISSUE THREAD

**Issue by PieBru** [sabeechen/hassio-google-drive-backup#54]
Hi Stephen,
Snapshots size increases daily and quickly becomes too big, particularly on the limited storage offered with free GDrive. SQlite DB old records historical storage and slack space are among the main, often unuseful, causes of this snapshots size increase.

Some "nice-to-have" ideas:

- an option to compact the SQlite DB by deleting old records and recovering slack space before each snapshot;

- to be able to abort a (huge) upload

- to be able to mark as "don't upload" queued uploads, temporary gaining time to cleanup GDrive space usage.

Btw, I'm managing pull/push/delete to my GDrive space by using Nautilus on my Arch Linux notebook. Nautilus GDrive support is not a full client, but its essential features (access GDrive as a virtual folder in a tab/window) are enough to manage the space and do a better usage of the precious cloud.
Rdrive seems also a nice up-to-date solution in Linux.

Thanks for your great addon, IMO it should be added to standard repositories.
Piero

**Comment by sabeechen** [comment]
> an option to compact the SQlite DB by deleting old records and recovering slack space before each snapshot;

I'm not familiar with how SQLite work in HA, but doing something before a snapshot should be possible.  How does one compact its database?
> to be able to abort a (huge) upload

I mentioned this in the other bug, but this is (to the best of my knowledge) a Hassio limitation.  It doesn't let you do anything with a started snapshot except wait for it to finish.
> to be able to mark as "don't upload" queued uploads, temporary gaining time to cleanup GDrive space usage.

I can see how this would be useful.  I'm in the middle of a release right now but I'll add that to a future one.  Could you give me a little more detail abuut how you'd use it?  I want to make sure we're on the same page.

**Comment by emouawad** [comment]
Following on this: "to be able to abort a (huge) upload" 

Just to clear this: @sabeechen you are saying it's impossible to stop a snapshot in progress - but does that mean an upload cannot be stopped too? since i guess upload is totally controlled by the addon no?
It would be fine to continue the snapshot creation and just stop the upload.

thanks for this wonderful addon and for your hard work!

**Comment by sabeechen** [comment]
Sorry its been a looooong while since I updated this bug, it kind of dropped off my radar.  A lot has happened with the addon since then.

The addon has a pause feature now, which allows you to stop uploads (or anything else the addon is doing) for 1 hour.  If someone needs more time than that, I recommend they just turn the addon off.

As for the sqlite compaction, I think that would be better accomplished as a standard HA automation, since I'd need to add in a lot of complicated customization to be able to handle all the use cases involved.  If you set the time of day for a snapshot and configure a compaction automation to run some time before that (plus a buffer) you could get the functionality you're asking for with as much flexiblity as you want.

I'm going to close this for now, but if you think there is something else  I could help with, feel free to reopen this, start a new issue, or ping me.
