### ISSUE TITLE
Error while backing up

### ISSUE THREAD

**Issue by nsf1977** [sabeechen/hassio-google-drive-backup#544]
Since a few weeks, and once in a while, I get an error [Errno 30] in google backup in the process of baking up a copy. All automations in Home Assistant still run, but everything that has graphs doesn't. I have some sensors (temperature, humidity, lux) reporting the values in graphs and when this error occurs they show empty with the loading spining wheel. I have a few Selly EM and when this happens the energy tab also shows as  empty whith the info "There is no data to show. It cas take up tp 2 hours for the new data arrive after configuring the energy panel".
To clear the error until it shows next time I have to turn off the instance running home assistant. Restarting it from server control makes it unavailiable and I have to turn it off and on.

I'm running google backup version 0.105.2

Here's the error log I get: 

addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

**Comment by sabeechen** [comment]
This is usually the result of something going wrong on your HA machine's hard drive, its unlikely to be caused by the addon. I've had a few users report this problem in the past, and the temporary fix has always been to restart the machine.   You should be able to take a look at Home Assistant or the Supervisor's logs when it starts acting up to see if it can give you some better information about what the problem is.

Linux will sometimes switch a hard disk into read-only mode if it thinks it needs to do so to prevent damage to the hardware. This can happen for a number of reasons:

  - Its out of space
  - The hard drive stopped responding
  - It detected corrupt data on your hard drive
  - Etc.

Restarting your host machine will probably make the problem stop for now, but I would recommend looking at the supervisor logs to see if it lists any problems when it starts up.  If the underlying issue is your hard drive (for example a worn out SD card)  I'd recommend replacing it.

**Comment by AmaralVini** [comment]
Every time doing a backup (using the addon or not) the Supervisor crashes and I have to reboot the machine. 

Some time ago I had to install the linux package ic2-tools and realized when I uninstall the package (apk del i2c-tools) and try to backup, it works. Then, after finish the backup, I have to reinstall (apk add i2c-tools). 

The install and uninstall actions can be executed calling shell_command service. So, it would be very useful if we can set these actions in the add-on configuration (before and after backup).

**Comment by sabeechen** [comment]
Sorry it took me a while to respond, I've been out of touch for some time.  I'd recommend doing the following to support this:

1. Set "Days between backups" to 0 in the addon's web-ui.  This will prevent the addon from creating any backups on its own.
2. Create an automation that runs at a certain time (eg 2AM) daily and calls the backup service between calls to your shell script to install/uninstall:
   ```yaml
   service: hassio.backup_full
   data: {}
   ```
The addon will still upload any backups it find to Google drive, regardless of where they came from.
