### ISSUE TITLE
Backup switched from full backup to partial backup

### ISSUE THREAD

**Issue by snowe2010** [sabeechen/hassio-google-drive-backup#584]
Not sure how to even log this. I've tested my backup solution before, so I know that full backups of my system _have been working_ for years in fact, with no issue. SD Card finally failed (I knew it would, but trusted the backups as they had been tested). By the time I got to retrieving the backups it seemed that this plugin had converted itself over to only doing partial backups, and lost all my full backups in the process (for some reason it did several partial backups on the same day, erasing the last several full backups). 

I have no clue why the plugin would do this, and I have no clue what the resolution could be, I just wanted to make an issue for it. I've since switched to using Core, so this won't affect me any more, but I thought others might want to know about it.

**Comment by sabeechen** [comment]
First off, I'm sorry you lost data.  The goal of this addon is to avoid data loss.

Did the backups have names like "Partial Backup YYYY-MM-DD HH:MM:SS" or did they have names like "core_XXXX.tar"?  Unless you tell it otherwise a supervised install will create a partial backup when updating Home Assistant or addons, they'll have a name similar to the latter example.  The addon (unless otherwise configured to do so) will then treat this partial "upgrade" backup as the latest backup.  If enough of them get created, you might run out of slots in Drive/HomeAssistant for the backups the addon creates.

If you use the addon again, you can enable the settings "Ignore Other Backups" or "Ignore Upgrade Backups" in the web-ui to make the addon ignore these types of backups.  If that isn't what happened, feel free to re-open this and I can try to dig into it further.

**Comment by snowe2010** [comment]
@sabeechen the backups all are `addon_<id>_<addonname>_version.tar` and there are only 4 of them

So are you saying that when addons update, they wipe out any trace of full backups? 

Seems like the default should be to trash backups rather than delete them outright then. I would have been able to recover my backups if that had been the case. I didn't know this was how the backups worked (no clue how I could have known, as I would have had to check Drive immediately after upgrading addons to see this right?)

**Comment by sabeechen** [comment]
Yes, by default the addon treats every backups it sees the same way regardless of how it was created.  If the 4 latest backups are from upgrades and you only keep 4, then it will delete all of the non-upgrade snapshots.

Its kind of a tricky issue.  If I default one of the "Ignore other backups" to true, then my users who *do* want these partial backups uploaded to Google Drive will find that the addon silently ignores them, causing a different category of data loss.  For stability reasons I also try *very* hard not to introduce changes in behavior with updates that can break existing users workflows.  Some people only use the addon upload snapshots to Google Drive and use an automation in Home Assistant to create snapshots on a more custom schedule.

That being said you aren't the first person to have this problem and I feel like I need to do something smarter about it.  Its confusing and surprising behavior for new users, most people don't even notice that there is a checkbox asking of you want to create a backup every time you update an addon.  Even those who notice it probably don't connect the dots and realize it will cause them to lose a "full" snapshot.

So maybe I could do this:
  - Make the "ignore upgrade snapshot" default to true only for new installations.  That way new users won;t see this happen.
  - For existing users who upgrade, display a one-time notification in the web-ui the first time it encounters an "upgade" backup that pushes out a full backup and recommend turning on the option to ignore it.

This way I don't break the existing workflow for users who have been using the addon for a while (unless they explicitly indicate to do so in the notification) and it stops being a problem forever for new users.

**Comment by snowe2010** [comment]
Those I think are reasonable solutions, but is it not just possible to default to moving stuff to the trash rather than deleting outright? I would expect to have at least 30 days to recover these things from google drive's cache, and in my mind, that is actually more confusing than the settings being the way they are. I completely understand why you haven't changed those settings at this point, as not wanting to break stuff for [each category of user](https://xkcd.com/1172/) is a perfectly valid reason to keep it as is.

**Comment by sabeechen** [comment]
The problem with putting backups in the trash (instead of deleting them) is that it still counts toward your storage quota.  I could add this as an option in the future, but if I made it the default anyone running the addon at-or-near their Google Drive limit would have the addon stop working after a bit.  For example even someone with a conservative 500Mb backup size would see their free quota exhausted entirely by the trash with daily backups after 2 weeks, requiring some intervention to continue working.

Note: This isn't the case for some rare circumstances.  If the addon is backing up to a Shared Drive and the user linked doesn't have permission to delete from the Shared Drive (eg "Content Manager" instead of "Manager") it will move items to the trash instead of deleting them.  This doesn't create a quota problem because Shared Drives have effectively unlimited quota.

**Comment by snowe2010** [comment]
Hm. ok. I see. Are the backups usually that large? I'm guessing that's mostly just the log data right? Difficult problem to solve for sure... Thanks for thinking about this!

**Comment by sabeechen** [comment]
I think its usually the database, but I can't be certain.  From the metrics I get from Google about API usage associated with the addon I can see that the most common error people have is from running out of storage quota.  Since Google gives you 7GB for free and the addon stores 4 backups by default, I suspect a large percentage of my users have backups over 1GB.  I also think there are a lot of people who install the addon and then never check on it, despite how much it complains when it runs out of space.

**Comment by sabeechen** [comment]
Took me a while, but I've implemented this as of v0.108.2.  For new users, the default behavior is for the addon to ignore upgrade backups.  If an existing user upgrades and doesn't have either of the ignore options turned on, the addon won't change its behavior automatically but will present a dialog in the web-ui recommending that they turn on the option on.

**Comment by snowe2010** [comment]
Thank you so much! I hope this helps out others! Thanks for the hard work.
