### ISSUE TITLE
Backups not recognized. Can't restore!  Error says not a gzip file

### ISSUE THREAD

**Issue by jaysettle** [sabeechen/hassio-google-drive-backup#596]
I have 4 backups(backed up with google drive backup) and have tried to reload all of them but keep getting this error:
```
 Can't read tarfile <securetar.SecureTarFile object at 0x7f932b2ed940>: not a gzip file
```
I lost my good HA OS and can't currently restore it! **Anyone else having this problem?**

Within google drive backup add-on, when I click on all of my backups it states that everything is there.

![image](https://user-images.githubusercontent.com/603364/165013630-94b4ac19-bc38-4eb9-bc98-5c2b7f5365c0.png)

**Comment by sabeechen** [comment]
Sorry it took me a while to get back to you about this.

It is tricky to offer advice about how to fix this without more information.  You can answer a lot of questions I might have by using the  "Actions" > "Report a bug" feature in the addon's web-ui.  If you do this right after attempting to restore the backup, the logs may be helpful to me also.

Despite that, here is what I can tell you.

The addon never actually creates the backup, it just asks Home assistant to do it and uploads what it gives back to Google Drive.  That means there are only a handful of things that could be the problem.

1. A bug in Home Assistant made a corrupted backup.
2. A bug in Home Assistant prevents you from restoring a backup.
3. You are trying to restore a password protected snapshot with the incorrect password
4. Physical corruption on the hard drive (a worn out SD card for example) has corrupted the snapshot.
 
Bugs in Home Assistant are possible but I can't really do anything about it, and I can't help with an incorrect password either, so I'll try to address the  hard drive corruption angle.  Since Home Assistant can read the metadata for the backup (eg you can see its contents in the ui) that means it isn't completely corrupted.  Most likely just one or a few of the addon's inside are corrupted if thats the problem.  If the snapshot is not password protected you can try downloading the backup to your computer and opening it with a compress/decompress utility (I recommend [7-zip](https://www.7-zip.org/)).  Inside of the main tar file you should see something like this:
![image](https://user-images.githubusercontent.com/21026774/166482642-913303a3-dc63-42ea-9034-a2244acba9e1.png)
In addition to a metadata file (backup.json)  you'll see one compressed archive for each folder (homeassistant.tar.gz, share.tar.gz, etc) and one for each addon (XXXXX_addon_name.tar.gz).  You should be able to open each of those and see your files/configuration.  If you can't open one then it is probably corrupted.  If you can determine which one it is, then you should be able to do a "partial" restore that recovers everything the corrupted folders and addons.

Also note that if your snapshot is password protected, you'll be able to open the main archive, but you won't be able to open any of the inner addon/folder archives.  The supervisor uses a custom encryption scheme that is unreadable by any compression utilities I'm aware of.  I think your best option in this case is to do a partial resotre of each folder and addon one at time.  Only the corrupted ones should fail.

**Comment by sabeechen** [comment]
I'm closing this issue for now but if there is any other way you think I can help please feel free to reopen it and let me know.
