### ISSUE TITLE
error during month backup deleting

### ISSUE THREAD

**Issue by sky7176** [sabeechen/hassio-google-drive-backup#602]
Good morning,
my backup system set up like this:
7 daily
4 weekly
12 monthly
1 years

Now, if as regards the daily and weekly, I do not receive errors for the cancellation of the old backups,
every month, when deleting the old monthly backup, in this case May 2021, I receive a notice that I report below:

`The add-on attempted to delete 2 backup(s) from Google Drive and 0 backup(s) from Home Assistant. Under normal circumstance, the add-on will only delete one backup at a time (the oldest). This warning is produced to prevent the add-on from accidentally deleting your history of backups. This is normal if you recently lowered the number of backups to keep in Google Drive or Home Assistant.

To resolve this you can:

    Review the settings add-on settings and increase the number of backups you keep.
    Click "Allow Deletion" below to permit these deletions to happen this one time.
    Click "Never ask again" below to permit the deletes this time and in the future (not recommended)`
	
	
From what I understand due to the fact that the backup software is deleting, on google drive, 2 backups instead of just one

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.106.2`
 Home Assistant Version: `2022.4.7`
 Supervisor Version: `2022.04.0`
 Supervisor Channel: `stable`
 Hassos Version: `7.6`
 Docker Version: `20.10.9`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-05-01T06:12:06.931355+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2022-05-01T05:15:21.197665+00:00`
 Last Good Sync: `2022-05-01T05:15:19.506926+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:176 (sync)
  addon/backup/model/model.py:335 (_purge)
backup.exceptions.exceptions.DeleteMutlipleBackupsError: {'HomeAssistant': 0, 'GoogleDrive': 2}

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-04-30T22:00:03Z",
        "max": 1,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 27,
        "size": "371.5 MB",
        "ignored_size": "2.4 GB",
        "free_space": "92.4 GB"
    },
    "GoogleDrive": {
        "backups": 23,
        "retained": 0,
        "deletable": 23,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-04-30T22:00:03Z",
        "max": 30,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "6.1 GB",
        "ignored_size": "0.0 B",
        "free_space": "6.7 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 1,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 30,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.IGNORE_UPGRADE_BACKUPS": true,
    "Setting.BACKUP_TIME_OF_DAY": "00:00",
    "Setting.BACKUP_PASSWORD": "REDACTED",
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 4,
    "Setting.GENERATIONAL_MONTHS": 12,
    "Setting.GENERATIONAL_YEARS": 1,
    "Setting.GENERATIONAL_DELETE_EARLY": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```

 Thancks
Giuseppe

**Comment by sabeechen** [comment]
Thank you for bringing this to my attention and providing so much detail, it really helps me narrow down the problem quickly.  you get the rarely-awarded "awesome issue" label.

I think this issue can manifest any time you have configuration in which:
 - The generational backup periods (eg days, week, months and years) have some overlap
 - You schedule backups between 00:00 and 01:00
 - You have "purge early" enabled for  generational backups.

The issue is that as time crosses over one of the overlapping boundaries (ie where 7 days overlaps a week or 12 months overlaps a year), the addon also creates a backup which causes two older backups  in the overlap to be un-needed (because of delete early).  Its kind of hard to explain it, its a complex interaction.

I will need to do a little work to accurately have the addon tell the difference between this case and an unintentional misconfiguration thats going to nuke a bunch of backups, but I'll release a fix for it soon.

In the mean time if you disable the "Purge Old Backups Early" option in your generational backup settings I think you can avoid this warning until I'm able to release a fix.

**Comment by sky7176** [comment]
Thanks,
I have a month before the error recurs HI 

Giuseppe

**Comment by sabeechen** [comment]
I just published v0.107.1 of the addon, which should resolve this issue.  If you still see it after updating please let me know.

**Comment by sky7176** [comment]
OK, perfect,
as soon as I see it as an update I proceed.

For the tests I have to wait until next month, I have no idea how to simulate it, since it only happens to me with the monthly backup.

For the speech of the password, would it be possible to have the possibility to review it once typed?

Thanks for everything
Giuseppe

**Comment by sabeechen** [comment]
Sorry, I forgot you asked that.  You should be able to see your password if you go to, starting from the Home assistant main page:
<kbd>Configuration</kbd> > <kbd>Add-ons, Backups & Supervisor</kbd> > <kbd>Add-ons</kbd> > <kbd> Home Assistant Google Drive Backup</kbd> > <kbd>Configuration</kbd>

It will be in the text-box labelled ```backup_password```

**Comment by sky7176** [comment]
Many thanks.
I view the password into configuration of addon
Giuseppe
