### ISSUE TITLE
Cannot add addon to hassio!

### ISSUE THREAD

**Issue by hanynasyr** [sabeechen/hassio-google-drive-backup#62]
19-05-27 14:32:40 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_1ccucc: No such file or directory
fatal: index-pack failed
'.
19-05-27 14:32:40 ERROR (MainThread) [hassio.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup

**Comment by sabeechen** [comment]
Thats pretty strange, it looks like hassio is trying to download the add-on from GitHub, which isn't how the add-on is installed.  It should be trying to download an installation image from docker hub.

- What version of home assistant/hassos are you running?
- Are you able to install other add-ons?

**Comment by hanynasyr** [comment]
I am using hassos 2.11 and I dont have any issues adding other addons

**Comment by Cooper-Dale** [comment]
Same problem with fresh, clear install on RPi3+ HassOS 2.12
`19-08-18 20:16:52 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
19-08-18 20:16:58 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/sabeechen/hassio-google-drive-backup repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: Unable to create '/data/addons/git/cebe7a76/.git/shallow.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.'.
``
19-08-18 20:16:59 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/cebe7a76/repository.json: [Errno 2] No such file or directory: '/data/addons/git/cebe7a76/repository.json'
``
19-08-18 20:16:59 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/cebe7a76/repository.json`

`19-08-18 20:16:59 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
fatal: unable to open /data/addons/git/cebe7a76/.git/objects/pack/tmp_pack_iBauQd: No such file or directory
fatal: index-pack failed
'.`
`19-08-18 20:16:59 ERROR (MainThread) [hassio.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup`

**Comment by sabeechen** [comment]
Closing out older bugs today, please reopen if you think there is more I can help with.

**Comment by ihaettypo** [comment]
Having the same issue here, still not solved.

**Comment by sabeechen** [comment]
If you're seeing the exact same error message I suspect the fix is also the same, restart the host machine because git locked a file and won't let go (for some reason).  If that doesn't work for you let me know and I'll start looking into this again.
