### ISSUE TITLE
Failed backup data in tmp folder

### ISSUE THREAD

**Issue by donparlor** [sabeechen/hassio-google-drive-backup#633]
I had a failed backup initiated by your add-on and that seems to have left a large folder in /usr/share/hassio/tmp/ and it takes a large chunk of space on my SSD. My regular backups always exclude the media folder because I have a big music collection. When I installed this add-on, it automatically sets a complete backup and includes everything. When I realized this, I canceled out the backup but the unused space on my SSD was at an extreme low. I couldn't find a way to delete the data while the add-on was generating the backup thus I plugged my SSD as an external device on my main laptop and found out temporary files were located in usr/share/hassio/tmp/. I identified the large file and deleted it. 

Is there a way to delete those leftovers from Home Assistant? And should the add-on keep an eye at those failed backups?

**Comment by sabeechen** [comment]
The backups and that temp directory are both managed by Home Assistant (the Supervisor specifically) and unfortunately this add-on doesn't have any control over them.  

I believe that normally the supervisor will clean up temporary files in that directory created during backup, even if a snapshot fails, but if its interrupted in the way that you did I'm not sure what it would do with the files left over.  My best guess is that it would clean up files in the temp directory within 24 hours or after a restart, which is standard for most linux system.

If you need to interrupt a backup in the future, I'd recommend rebooting the Home Assistant machine instead since that will cause a cleaner shutdown, AFAIK there is no other way to interrupt Home Assistant once it starts making a backup.  

To avoid this problem in the future, when you install the addon you can change the settings before connecting it to Google Drive if you'd like to change how it backs up (eg to exclude a folder).   The add-on shouldn't create a backup until you connect it to google Drive.

**Comment by donparlor** [comment]
Thanks for your advice! I already uninstalled, reinstalled, configured then started the add-on. All is working properly now.
I just think there is a loophole here that can cause serious headache potential for someone who doesn't know where to look in case they fell into that backup interruption scenario. Great add-on @sabeechen! Thanks!
