### ISSUE TITLE
after firmware upgrade, backup system restore after the old firmware version is displayed

### ISSUE THREAD

**Issue by Lesboy72** [sabeechen/hassio-google-drive-backup#637]
If I upgrade the firmware of a zigbee device to the latest version and then restore an earlier backup, the old firmware version number will be displayed in the zigbee device data. Clicking on an update search will no longer yield results, as the latest firmware was previously installed on the device, I just can't see the latest version number due to the backup. Is there a way to get the latest version number on the device when backing up?

**Comment by sabeechen** [comment]
You might want to reach out to the people who maintain the zigbee add-on/integration you're using.  Thsi add-on just saves and restores files, I'm not familiar with how the zigbee component maintains its data.  Even if I was though, I don't think I'd be able to do anything about it from _this_ add-on.  My best guess is that they're not getting this version number from the device itself and instead storing in a database somewhere so that after being restored it thinks the device has old firmware, but again that's just a guess.  The developers who maintain the add-on or integration you're using will need to address this if there is something wrong.

**Comment by Lesboy72** [comment]
Thank you your answer.
