### ISSUE TITLE
Binary sensor states capitalized

### ISSUE THREAD

**Issue by jacobbjo** [sabeechen/hassio-google-drive-backup#64]
I just installed this awesome addon but I noticed that the binary sensor has the state "False" (capitalized F).

I'm not sure if I'm correct of if it matters but I think the states should be written in lower case (false/true).

["These sensors only have two states: 0/off/low/closed/false and 1/on/high/open/true."](https://www.home-assistant.io/components/binary_sensor/)

**Comment by sabeechen** [comment]
Home Assistant doesn't seem to care either way, but I'll change it to lower case regardless in the next version just to follow the convention.

**Comment by sabeechen** [comment]
As it turns out, I think the add-on is already doing this the "right" way.

Technical stuff ahead:
The add-on tells Home Assistant to store the sensor state as a boolean value, ie true or false.  I believe the reason it shows up capitalized in the UI is because the UI is written with python, which by default capitalizes booleans when rendering them as a string, ie `True` or `False`.  I could tell Home Assistant instead to store the sensor state as a lowercase string (ie `true` or `false`) which should still work, but I think it better to store the state as its _real_ data type (a boolean) and let Home assistant decide how to render it on the webpage.

If you still think I got this wrong, feel free to reopen the issue and I can look into it further.
