### ISSUE TITLE
Restore page does not give a "Restore" option.How do I restore now?

### ISSUE THREAD

**Issue by mebrew** [sabeechen/hassio-google-drive-backup#66]

**Comment by mebrew** [comment]
I am trying to restore an instance of Hassio but there is no option to do so, only a DOWNLOAD option. How do I then restore from there please?

**Comment by sabeechen** [comment]
The snapshot has to be copied back to your Hass.io instance for it to be restored, you can do this by selecting `ACTIONS > UPLOAD` (which uploads directly from Google Drive) or by manually copying it from your Google Drive folder into the `/backup` folder.

Once its there, you can restore the snapshot from Hass.io's normal snapshot restore page.

**Comment by mebrew** [comment]
Hello Stephan,

Thank you for your reply.

I think I have followed your instructions. The google backup is now in the /backups folder - 



I have clicked the “restore” button but nothing appears to happen, any helpful tips ?

Sorry to be a pain.

Regards

Michael

**Comment by sabeechen** [comment]
No pain, I'm here to help.

The restore link just redirects you to Hass.io's snapshots page, for some reason that link must not be working for you.  You can get to the same place from the Home Assistant interface by going to `Hass.io > Snapshots`.  The snapshot you uploaded back should show up there, if not try clicking the refresh icon at the top right of the page.

**Comment by mebrew** [comment]
Hello Stephan,

Thank you for your reply.

I think I have followed your instructions. The google backup is now in the /backups folder

**Comment by mebrew** [comment]
Hi,

Sorry,Stephan I must be totally thick. I thought I was restoring the google drive image from the snapshots page. 

If I am doing something wrong can you please STEP BY STEP me through iy.

I am still a novice with HA and don’t want to mess up

Thank you

Michael

**Comment by mebrew** [comment]
Hi, Stephan,

Should I see a message that the restore is working? Please

Michael

**Comment by sabeechen** [comment]
Yeah, its kind of difficult to figure out how all the pieces in Home Assistant and Hass.io work together.  Don't worry too much about doing it wrong, so long as you have your snapshots in Google Drive you shoudl always be able to start over and restore from a fresh install if something gets messed up.

First some context that might make things clearer.
* Hass.io does all of the work to create and restore snapshots.  This add-on only tells Hass.io when to create a snapshot and then copies it to Google Drive once completed.  Because of that, you have to use Hass.io's webpage to actually restore the snapshot.
* Hass.io can't restore a snapshot unless it exists in the /backup folder.  Thats why you either need to copy it in yourself or use the `ACTIONS > UPLOAD` menu I mentioned earlier.  Hass.io can't directly restore a snapshot from your Google Drive folder.
* When you restore a snapshot, you can do a full or partial restore.  Full restore overwrites everything with whats in the snapshot, and with a partial restore you can select which folders (eg the /config folder with your configuration.yaml) and add-ons you'd like to restore.

Assuming you already have the snapshot you want to restore in the /backup folder, you first need to go to Hass.io's snapshot page:
* Open your home assistant home page (for most people https://hassio.local:8123)
* From the side menu click "Hass.io"
* From the top menu click "Snapshots"

The snapshot you intend to restore should show up on this page.  If not, click the refresh icon in the top right of the page (note: not a browser refresh!) and wait a few seconds.  If its still not there, you'll need to try copying it over again or use "ACTIONS > UPLOAD" again from this add-on's web-ui.  If its still not showing up, try clicking "System" at the top of the page and see if the logs show any errors.

To restore a snapshot:
* Click the one you want to restore.
* Select `Wipe & Restore` to do a full restore (overwrites everything with the snapshot's contents) or select just the parts you want to restore and click  `Restore Selected` to do a partial restore.
* It will probably take between 2 and 20 minutes for the restore to complete and Home Assistant/Hass.io to restart.  There is no dialog saying when its finished, but usually the interface will warn that the connection has been lost (because its restoring) and then come back online once its done.
* Refresh the webpage.

Hope that helps!

**Comment by mebrew** [comment]
Hello Stephan,

Your guide was brilliant !!!   Thank you so much for your help. I have managed to restore a working copy of HA after I screwed something up.

Can I suggest you add your guide to a wiki or something, so that other be-nighted soals can plough through easier.


Thank you again

Kind regards Michael
