### ISSUE TITLE
Recorder ( MariaDB ) stop recording after backup done

### ISSUE THREAD

**Issue by cichy2k** [sabeechen/hassio-google-drive-backup#675]
I noticed today that home assistant recorder ( mariaDB ) stop working until done restart after backup.

**Comment by duttry14** [comment]
I have experienced the same issue. Daily upon completion of my automated backup to Google Drive mariaDB will no longer record events. Events still occur and trigger items in other addons (example Node Red flows). Upon restarting Home Assistant new events are recorded/tracked (have been restarting daily for the last ~5 days).

**Comment by sabeechen** [comment]
The ways I can help with this are limited, let me explain why.

This add-on doesn't actually create backups, it just asks Home Assistant to create one similar to if you went to the backups web-ui within Home Assistant and made it there.  Home Asisstant is what actually packages up the backup, pauses/resumes addons, etc.  This backup add-on just takes the package Home Assistant gives it and uploads it to Google Drive.

MariaDB has always been a problem for backups (see [this history of issues](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=is%3Aissue+MariaDB)), and I've never been able to do anything about it.  Addon's are _supposed_ to automatically pause and resume during backup, but MariaDB has often had problems doing that, my guess is thats whats happening here.  I can't be 100% certain of that, but historically every problem with MariaDB and backup has been caused by something I have no influence over.

There are a few things you could try:
1. Consider opening an issue on the [MariaDB Add-on GitHub](https://github.com/home-assistant/addons/tree/master/mariadb).  There are already some open issues there for the MariaDB add-on, but I'm not confident any of them are/aren't the same issue you're seeing.
2. In this backup add-on, you can configure it to stop certain add-ons while taking a backup (check the settings).  This isn't ideal, you might lose some sensor history if your backups take too long, but it should work around the issue for now.
3. You can also configure the add-on to exclude MariaDB from the backup (check the settings).  Obviously not ideal but it also works around the issue until MariaDB is fixed or the problem is identified.
