### ISSUE TITLE
Feature Request: Auto Dark Theme

### ISSUE THREAD

**Issue by Ra7t0r** [sabeechen/hassio-google-drive-backup#688]
Hello.
It would be great if the web UI automatically changes to the appropriate light/dark theme based on HA system current theme

**Comment by tismofied** [comment]
Yes please

**Comment by sabeechen** [comment]
Home Assistant doesn't expose an API to see what its current theme is (at least not one I'm aware of) so to replicate its theme I'd have to do some unpleasant iframe hackiness that's likely to break when HA changes how they do things.

What I _can_ do is respect what the browser's current dark/light setting are.  I'll set it up so that if your accent/background colors are set to the default value (or unset) then it will use a dark/blue theme for dark mode browsers instead of the current default white/blue.  Not what you asked for exactly, I know, but I have to keep things maintainable. It'll be in the next release.

**Comment by tismofied** [comment]
Bless you!

**Comment by tismofied** [comment]
It's beautiful. My eyes thank you!!!


![image](https://user-images.githubusercontent.com/90809124/200463302-99577461-84af-4d52-add1-661c30e7ffca.jpeg)

**Comment by tismofied** [comment]
It's beautiful. My eyes are very grateful.


![image](https://user-images.githubusercontent.com/90809124/200463609-6f280d90-1b92-43e6-b242-a4178c676358.jpeg)

**Comment by sabeechen** [comment]
Heh, you noticed fast.  

I've aded the automatic dark/light switching in v0.109.1, which I just released.  If you already have colors set and want to use the automatic colors, just click the "revert" link in the addon's color settings.
