### ISSUE TITLE
Problem backup, from 180 MB in size to 19 mb

### ISSUE THREAD

**Issue by Niconaco** [sabeechen/hassio-google-drive-backup#696]
Ciao, ho questo problema, di solito i miei backup sono di circa 180 MB, da qualche aggiornamento scorso di home assistant me li crea a circa 19 mb, se faccio il restore di quel backup da 19 MB home assistant non funziona, come sistemare? grazie, ecco il file di log, grazie.
[home-assistant-google-drive-backup (1).log](https://github.com/sabeechen/hassio-google-drive-backup/files/9364341/home-assistant-google-drive-backup.1.log)

**Comment by sabeechen** [comment]
Non so perché i tuoi backup siano diventati più piccoli, dal momento che fai backup completi ci deve essere stato un add-on o una cartella che non era più grande come prima. Dovresti aprire uno dei backup più grandi e guardare i file per vedere cosa è cambiato. Questo add-on chiede solo a Home Assistant di creare backup e poi di caricarli su Google Drive. Non sa cosa c'è dentro i backup.

Quando il ripristino di un backup non riesce, l'unica cosa che puoi fare per capire cosa è andato storto è guardare i log. Di solito questo significa collegare un monitor e una tastiera al computer e usare questi due comandi per visualizzare i log del Supervisor e di Home Assistant (ad esempio, "core"):
```
supervisor logs
core logs
```

Original English (above is a machine translation):
I can't know why your backups got smaller, since you're doing full backups there must have been either and add-on or folder that wasn't as big anymore.  You would have to open up one of the older larger backups and look at the files to see what changed.  This add-on only asks Home Assistant to create backups and then uploads them to Google Drive.  It doesn't know whats inside the backups.

 When restoring a backup fails, the only thing you can do to figure out what went wrong is look at the logs.  Usually this means hooking up a monitor and keyboard to the machine and using these two commands to look at the Supervisor's logs and Home Assistant's (e.g. "core") logs:

```
supervisor logs
core logs
```

**Comment by Niconaco** [comment]
Risolto, grazie!

**Comment by sabeechen** [comment]
Prego!
