### ISSUE TITLE
Migrate your impacted OAuth out-of-band clients to an alternative method

### ISSUE THREAD

**Issue by PanMat** [sabeechen/hassio-google-drive-backup#702]
I got following message from Google Developers:

https://imgur.com/a/AoClTJP

Has anyone else seen it or better solved it?

**Comment by sabeechen** [comment]
If you followed [these instructions](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md) before June 2022 to generate your own credentials to use with Google Drive you'll need to go through them again (starting at [step 3](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/LOCAL_AUTH.md#step-3---create-a-consent-screen)) to regenerate your credentials.  You can just follow the instructions again, paying attention to the notes I've added for those only needing to regenerate the credentials.  If you're using an up-to-date version of the addon, it should have notified you about this in the web-ui if you could be affected.

This is necessary because Google changed the requirements for how developers create their credentials.
