### ISSUE TITLE
impossible to start the addon

### ISSUE THREAD

**Issue by jymorel** [sabeechen/hassio-google-drive-backup#706]
After installing the add-on, the "start" button has no effect. The "restart" and "stop" buttons don't appear.
When I click in the sidebar on “Backups”, message “Add-on is not running. Please start it first”…
Tried several times to uninstall/reinstall. Same issue.
No way to enter the configuration and enter my google account.
In the log, the server seems to be started and there are backup synchronization messages.

![add-on](https://user-images.githubusercontent.com/96637729/188128498-73d1d6c0-8e1f-4c21-8947-5089c359fa7c.jpg)
![log](https://user-images.githubusercontent.com/96637729/188128500-7682ef08-a41b-4c6d-96cc-1e58c24559b4.jpg)
![side-bar](https://user-images.githubusercontent.com/96637729/188128501-1c046f06-8911-4027-89e7-43a9d7177004.jpg)

**Comment by robertoleonardo** [comment]
+1

**Comment by jymorel** [comment]
Solved...
I don't understand. I didn't touch anything. And tonight, several hours after installation, I was able to access the add-on configuration and the backups are running.

**Comment by sabeechen** [comment]
The logs indicate the addon _is_ running, so I'm not sure why Home assistant says it isn't.  If either of you see this again, could I ask that you check the supervisor's logs to see if it shows any errors?  Problems starting an addon should show up there.

**Comment by robertoleonardo** [comment]
sure will do if it happens again -- and thanks for an awesome add on stephen.

**Comment by robertoleonardo** [comment]
by the way - may or may not be a helpful data point, but in case it is, something i just remembered about my tinkering with the issue yesterday:

i compulsively take snapshots of my home assistant so whenever i have an issue like this, i have like 5 backups that i can jump to without losing any updated settings. so when i first got the issue, i restored a snapshot. for like the first time ever that didn't fix the issue. tried several more snapshots, and it continued to persist. tho not sure if i've ever had add in related issues like this. think they're usually integrations giving me problems. so that might explain the distinction.

anyway, i am now remembering that i think what DID get mine working again was just a full rpi reboot -- not just a hassos reboot (which i guess is all that happens when restoring a snapshot).

all that said -- no idea if that's at all helpful. i'll never have anything more specific thank a VERY broad strokes understanding of core vs supervisor and how they work together, sooooo i'm just winging it

**Comment by sabeechen** [comment]
A couple other user have reported issues starting the add-on, though I'm not sure if they're all the same problem. I suspect something about the docker environment the supervisor manages is getting messed up, which might explain why a reboot fixes things.  Many docker problems can be resolved by restarting the docker engine.

**Comment by jymorel** [comment]
on my side, I'm using HAOS on raspberry pi4. Not docker. If I remember correctly, I tried several times to uninstall/reinstall the add-on and reboot only haos, but no success. I suppose that what solved the issue is a short power outage at home that caused a full rpi reboot. So same guess than robertoleonardo. Thank you for all the work for this great tool

**Comment by sabeechen** [comment]
HAOS uses docker under the hood, so does any version of "supervised" Home Assistant.

**Comment by jymorel** [comment]
Ah ok . I had a doubt. Thanks for the confirmation

**Comment by robertoleonardo** [comment]
weird that it happened to both of us at basically the same time yesterday, as i don't think it's ever happened to me before.
