### ISSUE TITLE
HA OS freeze during backup Full and Partial

### ISSUE THREAD

**Issue by RamiRihawi** [sabeechen/hassio-google-drive-backup#713]
My setup is freezing whenever the add on trigger automatic backup or when i manually trigger it myself.
The freezing issue does not occur immediately, after about two hours from starting the backup process.
I thought that might be due to the large size of media folder so i excluded it from backup yet the issue still exist.
I also stopped some of the CPU intensive other add-ons like Frigate but the same problem.

The HA would not start again until power cycle the System.

My setup:

Raspberry pi 4, 4GB 
HA OS
512GB SSD drive over USB 3

**Comment by sabeechen** [comment]
To provide some context know that this add-on doesn't actually create backups, it just asks Home Assistant to create them.  If something is locking up during a backup its almost certainly because of how Home Assistant (the "supervisor" specifically) is creating the backup.  Some addons additionally can cause periodic problems during a backup because Home Assistant needs to pause them while their files are read and compressed, such as with the MariaDB addon.

So there a couple potential causes:
- Even without the /media folder your backups may still be very large, for example if you have a large sensor history database in the /config folder or in the MariaDB addon.  A common problem is for some folder or addon to suddenly get large and then backups either take a long time or run out of disk space while trying to take the backup.  One time on my personal HA instance the sensor database randomly exploded to 100 GB and even compressed it ate up the entire hard drive and caused the system to fail miserably, HA will happily exhaust all available disk space and render itself unable to run if you ask it to make a huge backup.  Figuring out if this is your problem can be tricky because HA doesn't give you tools to see how much space a given folder or addon is using, but here are a couple tips:
  - You can create partial backups of just one thing at a time in the Home Assistant web-ui (<kbd>Settings</kbd> > <kbd>Backups</kbd>).  That can help you narrow it down, though it is quite tedious.
  - You can monitor free disk space in Home Assistant using the [System Monitor](https://www.home-assistant.io/integrations/systemmonitor) integration.
- Creating a backup is very CPU and disk intense, and the rpi doesn't have a lot of power to spare.  Some loss of performance is expected during a backup but I have also seen a system _appear_ to be completely unresponsive during a backup.  You can use the Glances addon to get an idea of whats eating up CPU during a backup, its in the Community Addon store and shows which processes are using CPU over a web-ui.
- If you're able to let a backup finish, eg your aren't running out of disk space and the backup actually just takes a long time because its big, then you should be able to see which part is taking a long time by looking at the backup's details.
- If none of that works, there might be something going wrong while the backup is being taken.  The most likely places to find clues for what that is are in the supervisor logs (recall that the supervisor is what actually creates the backup).  You can get the logs in a few different ways:
  - If the web-ui is still accessible, you can see them at <kbd>Settings</kbd> > <kbd>System</kbd>> <kbd>Logs</kbd>> <kbd>Supervisor (top right drop-down menu)</kbd>.  Please ensure you have "Advanced Mode" turned on in your Home Assistant user profile to make the logs accessible.
  - If the web-ui is unavailable, you can either:
    - Connect a monitor and keyboard to the raspberry pi, and run the command ```supervisor logs``` from the command line there.
    - Install the community SSH addon, connect to your Home Assistant machine over ssh (use [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/) or a similar terminal application) and run the command ```ha supervisor logs```

**Comment by bencollinz** [comment]
> My setup is freezing whenever the add on trigger automatic backup or when i manually trigger it myself. The freezing issue does not occur immediately, after about two hours from starting the backup process. I thought that might be due to the large size of media folder so i excluded it from backup yet the issue still exist. I also stopped some of the CPU intensive other add-ons like Frigate but the same problem.
> 
> The HA would not start again until power cycle the System.
> 
> My setup:
> 
> Raspberry pi 4, 4GB HA OS 512GB SSD drive over USB 3

I've been having this exact issue over the last 2 weeks. The only way to get it (rpi and HA) working is unfortunately pulling the plug.
I disabled the plugin this morning and waiting to see if that fixed it. My system would freeze within a few hours of restarting host.

**Comment by sabeechen** [comment]
If the system freezes within a few hours with the addon disabled, do you still suspect something is wrong with this addon?

Its difficult to think of something I can do with the information I have about this, as were not even sure if the addon is causing the problem.  Getting the logs out of a non-responsive HA install is difficult, were you able to have any luck with the ssh addon?  I've also seen some have luck persisting their logs using [shell command actions](https://community.home-assistant.io/t/hassio-0-102-1-just-froze-how-i-can-troubleshoot-such-issues/150998/9).

**Comment by bencollinz** [comment]
Mine's been running rock solid since disabling the addon a week ago. I just went with a different solution for my needs. Good luck, OP.

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
