### ISSUE TITLE
Google Drive Backup

### ISSUE THREAD

**Issue by MikeMcGlinch** [sabeechen/hassio-google-drive-backup#731]
I have not been able to get this running since installing it.  I am a newbie to this stuff.  Have tried reauthenticating several times.  Following is the logL

[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/9760514/home-assistant-google-drive-backup.log)

**Comment by bobmoran00** [comment]
Mine is also not syncing.  See Google comment at end.

10-14 14:58:59 DEBUG Making Hassio request: http://hassio/snapshots
10-14 14:59:00 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/hasource.py", line 174, in get   
    for snapshot in self.harequests.snapshots()['snapshots']:   
  File "/app/backup/harequests.py", line 63, in snapshots   
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")   
  File "/app/backup/harequests.py", line 132, in _getHassioData   
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))   
  File "/app/backup/harequests.py", line 98, in _validateHassioReply   
    resp.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots   
   

10-14 14:59:00 INFO I'll try syncing again in an hour

From Google:
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.
Request details: redirect_uri=https://philosophyofpen.com/login/backup.py

**Comment by sabeechen** [comment]
@bobmoran00, You'll need to follow [this comment](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877).  Your addon is very old and likely unable to update itself.

@MikeMcGlinch It looks like your addon is stuck in some kind of loop.  Could I have you add the setting "log_level: TRACE", restart the addon, and attach them again?  You'll need to add the setting through assistant's addon's config editor, the addon doesn't have the option in the web-ui.

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
