### ISSUE TITLE
binary sensor backups_stale not working as expected

### ISSUE THREAD

**Issue by daften** [sabeechen/hassio-google-drive-backup#738]
The last full backup that was completed (and uploaded to Google Drive) was a month ago for me. Since then, something went wrong, and my latest backup is pending. I'm still looking into that. But the main weird thing is dat the binary sensor backups_stale is still 'off'. I'd expect it to be on if the latest full backup is older than the normal backup schedule would make it be. So since I use daily backups, it should be on imo. Am I missing something?

**Comment by sabeechen** [comment]
The addon attempts to be conservative in how it determines if backups are stale.  If it thinks a backup needs to be made and sees that one is in progress, it will wait until it finishes before calling things stale.

This could lead to a situation where if a backup hangs indefinitely then the addon thinks that nothing is wrong.  Do you think this is what you're seeing?

It might be worthwhile for me to add an additional check for this, ie if there isn't a completed backup within a some time (maybe 1 or 2 days) from the last scheduled time then it triggers the stale sensor, even if one is in progress.  I want to avoid having the sensor trigger for people who have very long running backups, which is why I'm thinking a very long delay would be good.

**Comment by sabeechen** [comment]
In the latest version I just released (v0.109.1)  I've made the staleness sensor indicate a problem if no backup is present 24 hours after it was scheduled (or 24 hours after the addon was last restarted, whichever is later), even if a backup is in progress.  Let me know if it still gives you trouble.
