### ISSUE TITLE
Unable to backup files that exist in non-backed up folders

### ISSUE THREAD

**Issue by YashMaster** [sabeechen/hassio-google-drive-backup#767]
This might be a contrived situation, but I run the UniFi Network Application add-on, which stores its backups in ./backup/unifi folder. 
Unfortunately, I don't believe anything under ./backup/* is backed up by default (which is perfectly logical). However, in this particular situation, I'm unable to backup those files with my google-drive-backups. 

It would be great to have the ability to specify additional "included" folders. Maybe there's already a way to do this that I'm unaware of?

**Comment by sabeechen** [comment]
Home Assistant is the one who actually creates the backups this addon uploads to Google Drive, so this would need to be implemented on the Home Assistant/Supervisor side of things to make it happen.  This addon never actually gets to inspect or modify the contents of a backup. 

An alternative solution might also be to make the unifi controller's backup directory configurable (ie you could configure it to put backups int he /config directory or something), but it looks like the maintainer of the addon [explicitly does not want to do that](https://github.com/hassio-addons/addon-unifi/issues/406).

Really though, my question is why would you want to do this?  A backup you create with this addon should include a backup of the unifi addon's current config.

**Comment by YashMaster** [comment]
Thanks for looking into this @sabeechen ! I'm impressed you found my other issue with the Unifi Controller maintainer :D 

To answer your question about why I want to do this -- while it is true, a backup with this addon will include a backup of the unifi addon, the unifi addon backup is around 200-250 mb minimum (assuming minimal logging and history is maintained by the unifi controller). So this limits the number of backups I can maintain on my Google account. Considering the unifi-app's own backup file is less than a few hundred kb, it seems unnecessary to pay the overhead of backing up the full addon. I could just re-add the addon later and restore it separately. 

It's unfortunate the Google addon has no ability to modify the contents of the backup, but thank you for letting me know this. 

Alternatively, I attempted to resolve this problem by running a shell script to copy the unifi backup contents into an already-backed-up directory prior to executing a system backup. However, for whatever reason, the backup directory does not appear to be located in the same place when executing from whatever environment/user the shell scripts are run from (and surprisingly, I've been unable to find it). Do you have any insight to this?

**Comment by sabeechen** [comment]
Oh lol, I didn't notice that you actually made that Unifi controller issue.  I just thought someone else had your exact same problem.

OK so I'll try to give my best advice about getting the file out.  You are in a space where Home Assistant doesn't work well, so any solution is going to be a hack.  I'll also assume you've previously tried to run the copy command using the [shell_command](https://www.home-assistant.io/integrations/shell_command/) integration, which is where you ran into trouble, and that you're running some flavor of Home Assistant OS and therefore don't have access to the host computer's shell environment.  Home Assistant makes it quite cumbersome to do this kind of thing, I think on purpose.

The problem is that Home Assistant runs inside a docker container that the supervisor creates for it, and the supervisor doesn't mount the /backup direcoty inside that container.  There is no way for anything Home Assistant does to see the contents of the backup directory except through the supervisor's backup API, which doesn't expose this weird folder the Unifi addon creates.

So you'll need an environment that can see both the /backup folder and /config folder, and can execute the command to copy it.  The only way I'm aware of to do this is to use the Community "SSH & Web Terminal" Addon (check the add-on store for it)

Once you set up the addon with a username and password (which you won't actually use), edit the add-on's config in yaml to include the following init commands (whitespace and other are very important):
```yaml
init_commands:
  - echo "#!/bin/zsh" >> /etc/periodic/daily/backup_unifi.sh
  - >-
    echo "cp \`ls -1t /backup/unifi/autobackup | head -1 | read file; echo
    \"/backup/unifi/autobackup/\$file\"\` /config/unifi_latest" >>
    /etc/periodic/daily/backup_unifi.sh
  - chmod +x /etc/periodic/daily/backup_unifi.sh;
  - crond
```

These commands do the following when the addon starts up:
- Creates a script in /etc/periodic/daily/ with the following contents:
  ```bash
  #!/bin/zsh
  cp `ls -1t /backup/unifi/autobackup | head -1 | read file; echo \"/backup/unifi/autobackup/\$file\"` /config/unifi_latest
  ```
  Which copies the latest file in /backup/unifi/autobackup into the file /config/unifi_latest
- Makes the script executable
- Starts up cron, which will run the script daily (at 2 AM by default)

This isn't a great solution, since it spins up a whole docker cotnainer just to run one stupid command, but its the onyl way I coudl think of to make it work within these constraints.  My bash skills also aren't great, there is probably a cleaner way to write it.  Its pretty complicated but I think it would work quite reliably in practice.

**Comment by YashMaster** [comment]
Wow, you're awesome. This is hacky but it's also kinda beautiful. Because, not only does it seem like it would work, but it also is setup in a way such that even the creation and registration of the script would be captured by the native system backup. Quite elegant, if you ask me. Thank you for going out of your way to share your knowledge about the inner workings of system and figuring out a way to solve this puzzle from within those constraints!

**Comment by sabeechen** [comment]
Thanks! I try to make things "not suck" but this example is probably as far as I'd go in the "suck" direction, for lack of alternatives.  I mean, it uses bash written in a yaml file to create a shell script that copies files from one mapped docker volume to another using an _entire virtualized machine_ to do that one simple task.  It kind gets to me that this is the state of the art in 2022, on an open source project on hardware you own and _ostensibly_ have full control over.  Why is it _so hard_ to just get the bytes to the place they need to go?  Are we just going to keep adding more layers of abstraction to our machines without modernizing the ones below to better suit the present?  It makes me worry that maybe humanity is on the wrong path, heading toward some abyss full of antiquated complexity, and future generations will look back with shame at at how we use technology today.  Can you believe that instead of reading the man page for the "ls" command, I just asked [GPT-3](https://beta.openai.com) to write it for me (to sort by last modified), AND IT DID.  I don't even know if its correct!  Things are getting weird, man.

I agree it would probably actually work well in practice from a maintainability and backup perspective.  If you go with it I'd also recommend the following:
- Disable the mapped ssh port (22) that the addon exposes, since you won't actually use it its just a potential security hole.
- Use the shell_command integration to make a sensor that looks at the last modified date of the unifi backup fiel in the /config directory and does soemthing, maybe a notification? If the date gets too stale.  I'd lose sleep at night worrying that the ssh addon maintainers change something and it makes the cron job fail.

**Comment by YashMaster** [comment]
Thanks again for all the recommendations. This seems like a solid option :)  
I agree, we are in a place where things are so abstracted, it's impossible to be an expert on every single thing. That said, I'm not sure where we go from here. I don't have any ideas on how things could be improved in the long run. But I am curious to hear your thoughts if you feel otherwise.

**Comment by sabeechen** [comment]
I wish I did!
