### ISSUE TITLE
Backup size went from 284MB 1 week ago to 2.3GB today.

### ISSUE THREAD

**Issue by jamieFL** [sabeechen/hassio-google-drive-backup#810]
Hello,

This is my first time asking for help on Git.  Last week, my backup was 284.6 MB and this morning's was 2.3 GB.  This week I've been working on Frigate, which has had me perplexed because it will not connect to my MQTT Server.  I also installed the Deepstack and Double Take add-ons, which have been running (Out of habit I checked start on boot). 

Even though the Frigate add-on has not started, there have been a lot of additions to the logs.  Could this be it?

How do I track down and rectify this?  I do not want to back up needless data.

**Comment by sabeechen** [comment]
Home Assistant's architecture and backup format makes this a little difficult to do, buts its not too bad.  Here is some guidance.

If you click on the addon in the web-ui, it will show you approximately how much space is used for each addon in the backup.  This only works for addons though.

The most sure-fire way is to download the backup to your computer and open it with something like [7-Zip](https://www.7-zip.org/), or your compression utility of choice.  Inside of the the backup (a .tar file) you'll find more compressed archives (.tar.gz files), one for each folder and one for each addon.  The files will have somewhat obscure names, but you can usually infer what they are, for example:
- "homeassistant.tar.gz" > the /config folder
- "ssl.tar.gz" > the /ssl folder
- "9a5a7364_hassio_google_drive_backup_staging.tar.gz" > The data folder for this addon
- "core_zwave_js.tar.gz" > The data folder for the z-wave addon

This should indicate which thing in Home Assistant is bulking up the backup.  But what to do from there?
If an addon is the cause, how to fix it will depend on the addon because Home Assistant doesn't let you directly modify the addon's file system.
If a folder is the cause, you should be able to further extract the folder's compressed archive and view the files inside.  You could then use an addon that lets you mess with Home Assistant's files, I recommend the "File editor" addon.

Special note:  If you protect your backup with a password, Home Assistant uses a very esoteric encryption scheme and the only way I'm aware of to get inside the inner compressed archives is to run [this command line utility ](https://github.com/sabeechen/decrypt-ha-backup) I wrote to decrypt them.
