### ISSUE TITLE
Virtual Machine Hangs during upload of Google Backup

### ISSUE THREAD

**Issue by pacioc193** [sabeechen/hassio-google-drive-backup#821]
Since some day, the virtual machine with Home Assistant OS hang during the upload of the backup into google drive.
System give back error : system-timesyncd.service : Watchdog timeout ( limit 3 min)! 
system-coredump[6195]: Process 106 (systemd.jurnal) of user 0 dumped core.

If i try to send a ACPI shutdown the Home Assistant didn't turn off but it exit from the hang. I've disabled this plugin and seems no problem at all.

When the system hang, also give some error about logger process that could not be execute and Google drive plugin error with timeout on upload the backup.

**Comment by sabeechen** [comment]
With a system hangs, usually the behavior is that the system becomes non-responsive, but it seems you're able to interact with it.  
- What is actually not working during the "hang", ie what indicates that there is a problem?
- It would be useful to know what the error message form the "lpgger process" and the addon are.
- Is the hang occurring while a backup is created, while it is being uploaded, or some other time?

If you're able to open the the add-on web-ui during the hang, you can use the "Actions" > "Report a bug" dialog to get a useful snapshots of your logs and settings.

**Comment by sabeechen** [comment]
Separately, it looks like that log message if from the system time sync service.  Is it possible you're experiencing hangs because you have the VM configured to go to sleep, [similar to the description here](https://access.redhat.com/solutions/5118401)?  Letting a Home Assistant machine go into a sleep mode would cause all kinds of problems.

**Comment by pacioc193** [comment]
During hang is not possible to use the webserver, it will not answer. If i send some command in the prompt command of homeassistant then the system exit from hang and start immeditely to answer to the web request. 
This hang happen during the uploading of backup. This virtualmachine run since 2 years and never create a problem... i can't underderstand why in the last week hangs so much... I will try to provide you some other logs

**Comment by pacioc193** [comment]
> Separately, it looks like that log message if from the system time sync service. Is it possible you're experiencing hangs because you have the VM configured to go to sleep, [similar to the description here](https://access.redhat.com/solutions/5118401)? Letting a Home Assistant machine go into a sleep mode would cause all kinds of problems.

About sleep mode... i never enabled it... could i check in someway?

**Comment by sabeechen** [comment]
> About sleep mode... i never enabled it... could i check in someway?

It depends on your OS, but assuming you're using debian 11 server variant you can

```bash
cat /etc/systemd/sleep.conf
```
Pretty much everything in that file should be commented out.

Though because its linux, there are a million confusing ways for it to be enabled.  A [google search for your os](https://www.google.com/search?q=debian+check+sleep+settings) is probably your best bet.

**Comment by pacioc193** [comment]
The OS is the one of homeassistant provide... not a custom installation

**Comment by sabeechen** [comment]
Ah, the prebuilt image probably isn't going to sleep.  That makes things more complicated, I'm not aware of a way to get a shell into one of the premade Home Assistant OS images, I think they intentionally make it impossible.  The Home Assistant CLI you get on the login page of the VM only lets you change Home Assistant and Supervisor configuration.

Its suspicious that using the CLI frees things up for you, because just opening the CLI and using a command doesn't do much.  Are you certain its the upload, and not taking a backup, thats causing the freeze up?  Its possible for a system running slower hardware to become very slugish during a backup (to the point that it appears locked up) because the backup is very IO intensive (it does compression and lots of disk writes).

You could test this by creating a full backup using the Home Assistant interface (Settings > System > Backups > Create Backup).  If you see the same lock up behavior, then its probably just the case your machine is struggling to do anything else while its making a backup.

**Comment by pacioc193** [comment]
I've changed from VirtualBox to VMWare... seems problem disappear... i will continue the test. Meanwhile i thank you very much for the support!!
