### ISSUE TITLE
Не проходит аутентификация 

### ISSUE THREAD

**Issue by felixburan** [sabeechen/hassio-google-drive-backup#837]
Не получается пройти аутентификацию,  выдает ошибку:  400: Bad Request. Раньше был установлен ваш аддон , и  аутентификация прошла мгновенно,  но  после восстановления их резервной копии , в которой ещё не было аддона- не получается пройти аутентификацию. Пробовал удалять из аккаунта google разрешение,  чтобы получить новый код - результат не меняется-выдает ошибку

**Comment by sabeechen** [comment]
In Russian:
Проблема, похоже, вызвана [этим изменением](https://github.com/home-assistant/core/commit/b033232b06e14759bd886204e2efd3347a8384be) в Home Assistant. Я выпущу исправление в ближайшее время, но пока вы можете обойти проблему, удалив любые начальные или конечные пробелы (табуляции, новые строки, пробелы и т. д.) из строки авторизации, которую вы вставляете обратно в дополнение.

In English:
The problem appears to be caused by [this change](https://github.com/home-assistant/core/commit/b033232b06e14759bd886204e2efd3347a8384be) in Home Assistant.  I will release a fix soon, but in the meantime you can work around the problem by removing any leading or trailing whitespace (tabs, newlines, spaces, etc) from the authorization string that you paste back into the addon.

**Comment by sabeechen** [comment]
Duplicate #833
