### ISSUE TITLE
show more logs then only from the last run

### ISSUE THREAD

**Issue by bkbartk** [sabeechen/hassio-google-drive-backup#842]
Hello Stephen,

I saw your message in the logs part, So I thought, let's just ask.
This morning at 2:10 my home assistant crashed, this is the time my daily backup is scheduled.
So I thought let's see if there is something in the log, but unfortunately I could only find the log of the last run, which was right after I restarted HA.
![image](https://user-images.githubusercontent.com/17070805/235419368-61cb3563-cf2a-4d91-a6a4-17107a3e7ff6.png)

I think it could be just as well not this add-on, but I would be great if I could see something in the log.
the HA log itself shows no useful information.

**Comment by sabeechen** [comment]
Unfortunately Home Assistant doesn't keep any logs after a restart or crash.  There isn't much I can work from with whats available here, but the most common reason for a crash during a backup is:
1. If you're running on a raspberry pi, a backup can use a lot of power (compressing, writing to disk) and if you have a undersized power supply it can cause instability.
2. Running out of disk space.  You'll often need roughly twice the space of a backup to create it (because of how HA creates backups).  A common problem is for something large to be added to the filesystem, causing the next backup to increase in size a lot and then unexpectedly run out of space.

So I can't say either of that is your problem, but if you're able to narrow down the problem and you think its soemthing I can help with, let me know.

**Comment by sabeechen** [comment]
Can you point me toward where ha keeps the logs on a crash?  I was unaware of this feature.

**Comment by bkbartk** [comment]
![image](https://user-images.githubusercontent.com/17070805/235747651-c992885f-f06d-4c98-80f0-cc779a2b4417.png)
in de config directory you have
home-assistant.log and home-assistant.log.1
home-assistant.log is the current log
where home-assistant.log.1 is the previous one.
when you restart the system the .1 gets deleted, the current one gets renamed. and a new one is generated.
so 2 restarts will still mess up some stuff.

also there is a .fault file, but in my case it's always empty, not sure what is there.

**Comment by sabeechen** [comment]
I wonder if the supervisor has a similar feature somewhere?  AFAIK the supervisor's logs are only stored in the docker container it runs in (which is just in-memory).  The reason this might help is that the supervisor actually creates the backup, so any problems it runs in to are most likely to be logged there.  This addon just asks the supervisor to make a backup and waits until its finished.

**Comment by bkbartk** [comment]
sorry, I don't know about that, But it would be strange if no log is kept at all,
