### ISSUE TITLE
Can't start add-on - docker-init not found error

### ISSUE THREAD

**Issue by redford-jones** [sabeechen/hassio-google-drive-backup#846]
I've been having an issue with this add-on since a reboot of my host this morning. I've since done multiple reboots, and repaired and rebuilt Home Assistant, including rolling back to an earlier backup, still no luck.

Error is as follows:
`Can't start addon_cebe7a76_hassio_google_drive_backup: 500 Server Error for http+docker://localhost/v1.41/containers/787f8275850b8ac55c75941e6b1acbeeb3af4254e0e3b4166c1bcee09fe9dcd2/start: Internal Server Error ("exec: "docker-init": executable file not found in $PATH")`

Running HA Supervised on Ubuntu on a NUC.

**Comment by sabeechen** [comment]
This error suggests the docker environment on your host OS is broken somehow, under the hood docker is used to run everything, including home assistant and this addon.  "docker-init" should always be installed and available.  Supervised Home Assistant doesn't handle this problem well.  Are you able to run any other addons?

If you're willing to restore from a backup and just want the problem to go away, rebuilding the OS on your NUC from a fresh copy of Home Assistant and then restoring your backup should create a clean environment again.

If the problem is related to just this addon, you also might be able to get away with just uninstalling and then reinstalling this addon.

**Comment by damiano75** [comment]
Same problem, only with this addon, I tried to uninstall and reinstall it, but it doesn't fix the issue...

**Comment by damiano75** [comment]
> Same problem, only with this addon, I tried to uninstall and reinstall it, but it doesn't fix the issue... Is there a way to install the previous version 0.110.4 of this addon?

Restarting the whole system, not only HA, fixed the issue in my case: HA Supervised on Debian on a MiniPC

**Comment by redford-jones** [comment]
Mine has randomly started working again now. Without any intervention from me. Odd. I'll close this issue as it seems to be a supervisor error.
