### ISSUE TITLE
HAOS/Proxmox ram jump usage after backup

### ISSUE THREAD

**Issue by benchristian88** [sabeechen/hassio-google-drive-backup#847]
Currently running HAOS in a VM on Proxmox, and have the Google Backup addon running a backup every 3 days.

Normal memory usage is about 2.8 GB, but after a backup, it jumps to 3.8Gb and holds there until a reboot of HAOS.  then in three days it jumps again.  if let it run without reboot too long all memory is taken up.  never let it get fully consumed so not sure if its just caching, normal linux etc.  

A restart doesn't clear it.  I don't know enough about the processes to look where its being held, 

the addon is consuming about 68mb of ram at idle, so it isn't that.  

Not sure where to look, but happy to get any logs if it will help, or close if this isnt an issue or already known.

**Comment by sabeechen** [comment]
Because of all the layers involved (Proxmox, docker, python's garbage collection, etc) it can be very difficult to tell if high memory usage is actually a problem.  Proxmox, for example, will not always report when used memory has been made available again by the virtualized OS, depending on how the memory is allocated and fragmented.  Are you seeing any symptoms of running out of memory, like errors in the logs or periods of time where the system locks up?

I should also mention in the past that I've gotten a number of bugs about memory/cpu usage from this addon but so far every time it has been a misunderstanding about how memory is managed in modern systems, it is an incredibly convoluted and opaque process from the user's side.  You gotta be really careful what number you trust from where.

Most likely the memory is being used by the Home Assistant supervisor, since it actually does the work of creating the backup.  Its also possible, if you have a large database, that the increased usage is because HA needs to buffer database writes in RAM while the database is being backed up.  Those should free up slowly after the backup completes and the database in unlocked.  In this case you'd see the increased memory usage in Home Assistant (with default settings) or the addon you use for your database (ie MariaDB).

The easiest way I know of to view whats going on with memory in Home Assistant is to use the glances addon.  It will display memory usage in summary and by container.  Home Assistant core, the supervisor, and this addon all run in their own isolated containers so the usage should be obvious.

**Comment by benchristian88** [comment]
thanks, your right, looks like the supervisor holding the memory after a backup.  full reboot fixes it.    interesting how its totally increements, so if you run the backup three times, it keeps escalating.    will log a ticket to ha.

**Comment by aperezva** [comment]
Hi

I have the same issue, please @benchristian88  could you tell how did you solved?

BR

**Comment by fabiankrauss** [comment]
@aperezva or @benchristian88  - any update on that? I see kind of the same behavior :(

**Comment by aperezva** [comment]
No news from my side. Waiting if @benchristian88 opened a issue to HA. But it’s seems that proxmox is reserving a cache in every backup similar to de size of it.

**Comment by glennwalsh** [comment]
I also am experiencing rapid memory growth with backups. @benchristian88 did you get a chance to log a ticket and have you had a response before I go into a bigger rabbit hole?

TIA
