### ISSUE TITLE
Support for new remote storage

### ISSUE THREAD

**Issue by cliffordwhansen** [sabeechen/hassio-google-drive-backup#856]
I have setup remote storage on HA 2023.06 :-)

The backup stats are still showing the usage of the SD card.
I created a backup (using HA) and it doesn't show up in the list, and when doing a backup via the addon it does not appear on the remote storage.

I have not had a look at the code yet, but my guess is that the new backup location is not exposed to the add-on container, and off-hand I am not sure how we can add it.

**Comment by sabeechen** [comment]
In my testing it looks like the addon can still see backups created directly in Home Assistant on a remote mount.  Ensure you dont have the option "Ignore Other backups" enabled in the addon's settings.  Even then, you should see the backup listed at the bottom under "ignored backups".  I'm using NFS, haven't tried with cifs.

It looks like they implemented this in a rather backward-compatible way, which I appreciate.  To support all of the new features, it looks like I'll need to do the following:
- Add some configuration to allow selecting (or overriding) the backup location.  They added it to the addon API, this addon just isn't reading it yet.
- The addon should read what the default backup location is and use that (instead of the default, to always use local disk).  In the supervisor docs it looks like there isn't an endpoint to read the default mount location, but I think thats just a documentation oversight, [it is getting returned by the API](https://github.com/home-assistant/supervisor/blob/main/supervisor/api/mounts.py#L31).  Regrettably it looks like [the only add-role that supports querying the /mount endpoint is admin](https://github.com/home-assistant/supervisor/blob/main/supervisor/api/middleware/security.py#L131), so this addon will need to request escalated privileges to request the list of mounts.  Maybe thats just an oversight in the API?   Its checked in and released though, no getting around that now if I want to support the feature.  Bummer.
- HA doesn't know anything about free space for remote mounts, so the UI shoul not display free space (and disable the safety check for free space) if you're using a remote mount.

**Comment by cliffordwhansen** [comment]
@sabeechen Ah right completely forgot about ignored, thanks
I am also using NFS.

Nice that it basically just works :-)

**Comment by Spirituss** [comment]
@sabeechen Looking forward for support new storage feature

**Comment by sabeechen** [comment]
I've implemented this as described in the just released v0.111.1.  Let me know if you run into any problems with it.
