### ISSUE TITLE
Unable to install version 0.111.1

### ISSUE THREAD

**Issue by wiabts** [sabeechen/hassio-google-drive-backup#889]
Hi, 
Running HA on proxmox and receiving the following error when trying to install:
![2023-07-16 19_28_37-Window](https://github.com/sabeechen/hassio-google-drive-backup/assets/106236027/bb56b68f-4f85-4cb0-a9f8-0c4384c09554)

**Comment by sabeechen** [comment]
I'd restart the machine.  I mean restart the whole machine, not just home assistant, since thats the only way to restart the supervisor.  Sometimes the supervisor's internal docker cache gets messed up and a restart is the only thing that  seems to clear it out.   If you continue to see the problem after that, please [see here ](https://github.com/sabeechen/hassio-google-drive-backup#supervisor_logs)about determining if the supevisor's logs have any useful details.

**Comment by allentcm** [comment]
I am having the same issue here is my supervisor log:
`23-07-18 10:01:40 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16020' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 134, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1015, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/sabeechen/hassio-google-drive-backup/': Could not resolve host: github.com'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 176, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError`

**Comment by azndoodle** [comment]
Same here; when I try to install, I got the same above error (original screenshot error).  I check the Supervisor log and I see this log entry:
`23-07-30 16:53:43 ERROR (MainThread) [supervisor.docker.interface] Can't install sabeechen/hassio-google-drive-backup-armv7:0.111.1: 500 Server Error for http+docker://localhost/v1.42/images/sabeechen/hassio-google-drive-backup-armv7:0.111.1/json: Internal Server Error ("layer does not exist")`

Is the reference of "localhost" the problem?

**Comment by sabeechen** [comment]
I believe the "localhost" part is just how docker references images internally.   Docker is what Home Assistant uses to run addons.  The steps are roughly:
* when you add the addon's repo: Home Assistant clones this the addon's install information from github
* When you install the addon: Home Assistant downloads the addon image from DockerHub

This is the only way Home Assistant provides for installing an addon.  If some part of downloading the information from Github or DockerHub fails, it seems like sometimes Home Assistant gets into a bad state where subsequent attempts will always fail.  Ive seen this from a lot of users, but I haven't really been able to do much about it.  Something is wrong in Home Assistant before any of the code I control runs.

The solution always seems to be:
- Uninstall the addon's repository in the add-on store
- Restart the host machine.  Don't just restart Hoem Assistant, the machine its on needs to be rebooted
- Add the addon's repo back
- Install the addon

**Comment by jianyu-li** [comment]
I am having the same issue now. tried uninstalling and adding the repo after a reboot but it's still not working

**Comment by realav** [comment]
`Can't install sabeechen/hassio-google-drive-backup-armv7:0.111.1: 500 Server Error for http+docker://localhost/v1.43/images/sabeechen/hassio-google-drive-backup-armv7:0.111.1/json: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument")`

I am also getting the same error.

**Comment by michaelmarconi** [comment]
I'm stuck with this too:

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 20:50:34 (1 occurrences)
Last logged: 20:50:34

Failed to to call /addons/cebe7a76_hassio_google_drive_backup/install - Can't install sabeechen/hassio-google-drive-backup-aarch64:0.111.1: 500 Server Error for http+docker://localhost/v1.43/images/sabeechen/hassio-google-drive-backup-aarch64:0.111.1/json: Internal Server Error ("layer does not exist")
```

And

```
23-11-02 20:50:34 ERROR (MainThread) [supervisor.docker.interface] Can't install sabeechen/hassio-google-drive-backup-aarch64:0.111.1: 500 Server Error for http+docker://localhost/v1.43/images/sabeechen/hassio-google-drive-backup-aarch64:0.111.1/json: Internal Server Error ("layer does not exist")
```

I did have this working previously and I'm super-keen to get it going again, as I have no remote backups now.

I've followed your instructions at: https://github.com/sabeechen/hassio-google-drive-backup/issues/889#issuecomment-1676463261 @sabeechen but no dice!

**Comment by sabeechen** [comment]
This issue keeps coming up!  I'm not sure if the error is in docker, Home Assistant, or this addon.

Looking around on the internet for when users of docker (not related to Home Assistant)run into this problem, it seems like it might be associated with with corruption in docker?

It looks like Home Assistant has a solution for this kind or corruption, though it requires access to your machine's CLI.  You can do that by either plugging in a screen and keyboard, or by installing one of the SSH addons from the addon store.  From the cli, could you try running:
```
ha supervisor repair
```

I was able to find at least khttps://community.home-assistant.io/t/installation-broken-after-update/358527/5 on the HA forums with a similar problem where this fixed it.  The documentation for this says it will `Repair docker issues automatically using the supervisor`, though I'm not sure exactly what that means.

**Comment by jianyu-li** [comment]
unfortunately a repair didn't fix it for me. Also if it helps (or complicates further) I'm not using docker for my setup

**Comment by sabeechen** [comment]
Home Assistant uses docker under the hood, so everyone using this addon is running it under docker (the addon isn't compatible with Home Assistant "Core").

I'm tired of feeling powerless to do anything about all the reports of this issue, so I'm going to try releasing the next version of this addon through GitHub's container registries instead of DockerHub, as most projects are doing these days.

**Comment by sabeechen** [comment]
Making an issue to centralize reports of this:
Duplicate #937

**Comment by michaelmarconi** [comment]
Thanks Stephen, hopefully that cures it!

Regards,
Michael Marconi
