### ISSUE TITLE
403 Client Error: Forbidden ("endpoint with name ... already exists in network hassio")

### ISSUE THREAD

**Issue by VivantSenior** [sabeechen/hassio-google-drive-backup#89]
Not sure if it's a addon or HA bug. After the update to 0.98.2 and click on "Start" to run the addon I have an error in HA --> System --> Log:

`ERROR (SyncWorker_15) [hassio.docker] Can't start addon_cebe7a76_hassio_google_drive_backup: 403 Client Error: Forbidden ("endpoint with name addon_cebe7a76_hassio_google_drive_backup already exists in network hassio")`

My config:
```
{
...
  "use_ssl": true,
...
  "require_login": false,
...
  "expose_extra_server": false
}
```

I remember that I had the same issue in the last addon version but after the hass.io / RPi reset I was able to start the addon but still would like to report this unexpected behaviour as a bug.

**Comment by sabeechen** [comment]
A [little searching](https://duckduckgo.com/?q=docker+%22endpoint+with+name%22&t=canonical&ia=web) leads me to think this is a bug in Docker (rather than the addon or Hass.io).  It looks like its been around for at least a few years.  It might be too late to ask, but are there any errors further up in the log?  That message makes me to think Hass.io was unable to stop the addon in the first place when you upgraded.  The reports I can find online about it say that restarting the docker engine is the only way to fix it (eg restarting hass.io).

**Comment by luki90pl** [comment]
I have the same problem, i cant start addon

**Comment by sabeechen** [comment]
Looking into this a bit more, it seems like restarting the host machine (or at least hass.io) is the only way to resolve this.  I can find many other references to this issue online, but they're all left either unresolved or abandoned.   [Another user who ran into this problem](https://github.com/sabeechen/hassio-google-drive-backup/issues/40) with this addon was able to get around it by:
* Uninstalling the addon
* Restarting Hass.io
* Reinstalling the add-on

The bug isn't in this add-on or even hass.io, its with the docker engine that hass.io is built on top of.  I don't think there is anything else I can do to resolve it.
