### ISSUE TITLE
Translation to non EN language

### ISSUE THREAD

**Issue by misa1515** [sabeechen/hassio-google-drive-backup#896]
Hello,
how may I translate this add on to e.g. Slovak language, please?

**Comment by sabeechen** [comment]
The issue is that the addon needs to be re-written, in the code, to allow translation.  This is difficult because because it was never written in the first place to support other languages, it wouldn't be a simple case of substituting strings.

At present I'm under a lot of time pressure from other sources and unable to put much time into support new functionality, I'm struggling just to make time to fix bugs.  Either this feature is going to have to wait until I have more free time or someone else is going to have to take over maintenance.


Duplicate #598
