### ISSUE TITLE
Password option not working

### ISSUE THREAD

**Issue by NasKar2** [sabeechen/hassio-google-drive-backup#911]
I'm using Home Assistant 2023.8.4
I've created a password in the secret.yaml file and used !secret google_backup in the password option for your add on.  After performing a manual backup TestPW. I download the file and then extract it to my local computer and it never asks for the password.
My log
`09-03 10:18:42 INFO Starting server on port 8099
09-03 10:18:42 INFO Server started
09-03 10:18:42 INFO Syncing Backups
09-03 10:19:40 INFO Requesting a new backup
09-03 10:21:04 INFO Backup finished
09-03 10:21:05 INFO Syncing Backups
09-03 10:21:05 INFO Uploading 'TestPW' to Google Drive`

**Comment by sabeechen** [comment]
Its the tar files inside that are encrypted, the main tar file is never encrypted so that the metadata about the backup is always readable.  If you try to extract the inner files using standard tools you'll find that they can't be opened.  This is how Home Assistant does its encryption, if you want to read an encrypted backup you can use [this tool I wrote](https://github.com/sabeechen/decrypt-ha-backup) beceause HA uses a non-standard encryption format.
