### ISSUE TITLE
Cannot re-install Addon

### ISSUE THREAD

**Issue by Mistermin** [sabeechen/hassio-google-drive-backup#934]
The add on worked perfectly up until today. Today I updated both supervisor as well as OS:

Core 2023.11.2
Supervisor 2023.11.0
Operating System 11.1
Frontend 20231030.2

I noticed that the add on stopped working. And clicking the Web UI didn't help unfortunately. Nothing in the add on log was registered. So I deleted the add on and tried to re-install it and received the following message:

Can't install sabeechen/hassio-google-drive-backup-amd64:0.111.1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.111.1&fromImage=sabeechen%2Fhassio-google-drive-backup-amd64&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/sabeechen/hassio-google-drive-backup-amd64/manifests/0.111.1": Get "https://auth.docker.io/token?scope=repository%3Asabeechen%2Fhassio-google-drive-backup-amd64%3Apull&service=registry.docker.io": EOF")

Could you please indicate what went wrong and most importantly: how am I to resolve this, TIA?

**Comment by gjoforte** [comment]
Same here! 

![Screenshot_20231111-165812](https://github.com/sabeechen/hassio-google-drive-backup/assets/15280453/9a8e950b-fb0b-45b2-a56f-32463faed9e2)

**Comment by sabeechen** [comment]
I'm in a situation where I can't really do anything about this, because its some kind of communication error between Home Assistant and DockerHub when its trying to download the image for the addon.  The image certainly exists where its trying to download it:
```
$ sudo docker pull sabeechen/hassio-google-drive-backup-aarch64:0.111.1
0.111.1: Pulling from sabeechen/hassio-google-drive-backup-aarch64
08409d417260: Pull complete
355a0f419466: Pull complete
44ed650c8b77: Pull complete
c98a4382767a: Pull complete
67a0391dde0c: Pull complete
f02dd5428fbc: Pull complete
afa6ea8a9f1e: Pull complete
b97a33b4b01a: Pull complete
845b39483c33: Pull complete
Digest: sha256:16d61271ad0f76422ef9a3cbfdfeea387c56de2ebf5c6bfded2f6b08e60d0290
Status: Downloaded newer image for sabeechen/hassio-google-drive-backup-aarch64:0.111.1
docker.io/sabeechen/hassio-google-drive-backup-aarch64:0.111.1
```
And I've been unable to do anythign to recreate this behavior locally.

I'm starting to think this might just be a problem with DockerHub, they've been pressuring "free" users like this project to get off their service.  HTTP 500 suggests the problem is entirely on DockerHub's side, maybe they're just having mroe issues as time goes on?  Pretty much everyone is hosting images on Github's container registries.  Time this project does the same, I think.

**Comment by sabeechen** [comment]
Creating an issue to centralize all the places people have reported this:
Duplicate  #937
