### ISSUE TITLE
tmp folders continuously created

### ISSUE THREAD

**Issue by michaellunzer** [sabeechen/hassio-google-drive-backup#972]
<img width="691" alt="Screen Shot 2024-01-07 at 2 47 19 PM" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/10967175/a0da53bb-a25d-435b-84c6-3e7508b6a1c4">
<img width="1162" alt="Screen Shot 2024-01-07 at 2 50 52 PM" src="https://github.com/sabeechen/hassio-google-drive-backup/assets/10967175/2cbf0963-6b4c-4e62-969f-373596f33fac">

Hi! 
I was searching in the issues and couldn't find anyone else with the same issue but I'm running Home Assistant 2024.1.2 as a VM on Proxmox. My HA VM keeps running out of space. In the samba share Backup folder I noticed that this addon continually creates temp folders [tmp+8 characters in the first photo] and it pauses this behavior when Home Assistant is out of space. The logs from the container don't reveal anything obvious - just say when a new backup is started. The logs inside the app open up in a new window but don't actually load. 

Any help would be appreciated!

**Comment by sabeechen** [comment]
I'm not sure what those temp files are, but I can give you a little context that might explain more.  

The add-on doesn't actually create backups, it just asks Home Assistant to create them.  Whatever is happening with those files its home assistant doing it.  One common problem that people run into with disk space is that they one day have a folder or add-on (media files, camera recordings, etc) that's much larger than it used to be, and the system runs out of space while trying to back it up.  

Because HA doesn't give much visibility into the progress of a backup, it can be difficult to figure out that's the problem.  A few tips are:

- The supervisor logs will print out what folder of add-on is being backed up.  You can watch this to see where it hangs or runs out of space.
- You can created partial backups of just one folder or add-on at a time, to see which one is larger than it should be.
